#!/usr/bin/env node
/* ============================================================
   build-party.mjs  —  party data extractor for the DM screen
   ------------------------------------------------------------
   Reads each player's character sheet (characters/<slug>/<slug>.html),
   pulls out its `const CHARACTER = {…}` object, computes the same
   derived numbers the sheet engine does (modifiers, save bonuses,
   initiative, passive Perception, proficiency bonus), and writes a
   combat-ready party file the DM screen loads:

       modules/the-weeping-grove/site/party.data.js
         -> window.WEEPING_GROVE_PARTY = [ {…}, … ]

   The character sheets stay the single source of truth — re-run this
   whenever a sheet changes:

       node modules/the-weeping-grove/build-party.mjs
   ============================================================ */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));            // .../modules/the-weeping-grove
const REPO = join(HERE, "..", "..");                            // repo root (dnd/)
const CHAR_DIR = join(REPO, "characters");
const OUT = join(HERE, "site", "party.data.js");

const ABIL = ["STR", "DEX", "CON", "INT", "WIS", "CHA"];
const mod = (s) => Math.floor((Number(s) - 10) / 2);

/* Pull the CHARACTER object out of a sheet and evaluate it (it's JS, not
   JSON: comments, trailing commas, unquoted keys). Bounded by the top-level
   `\n};` that closes the object at column 0 in every generated sheet. */
function extractCharacter(html, slug) {
  const m = html.match(/const\s+CHARACTER\s*=\s*\{[\s\S]*?\n\};/);
  if (!m) throw new Error(`No CHARACTER object found in ${slug}`);
  // eslint-disable-next-line no-new-func
  return new Function(`"use strict";${m[0]}\nreturn CHARACTER;`)();
}

/* Combat-relevant projection of a character + derived numbers. */
function toPartyMember(c, slug) {
  const level = c.level || 1;
  const profBonus = 2 + Math.floor((level - 1) / 4);
  const scores = c.scores || {};
  const mods = {};
  ABIL.forEach((a) => (mods[a] = mod(scores[a] ?? 10)));

  const saveProf = c.saveProf || [];
  const saves = {};
  ABIL.forEach((a) => (saves[a] = mods[a] + (saveProf.includes(a) ? profBonus : 0)));

  const skillProf = c.skillProf || [];
  const skillExp = c.skillExpertise || [];
  const percBonus =
    mods.WIS +
    (skillProf.includes("Perception") ? profBonus : 0) +
    (skillExp.includes("Perception") ? profBonus : 0);

  const portrait = c.portrait
    ? `../../../characters/${slug}/${c.portrait}`
    : null;

  return {
    slug,
    name: c.name || slug,
    player: c.player || "",
    race: c.race || "",
    cls: c.cls || "",
    background: c.background || "",
    level,
    ac: c.ac ?? null,
    maxhp: c.hpMax ?? null,
    hitDice: c.hitDice || "",
    speed: c.speed ?? null,
    profBonus,
    scores,
    mods,
    initMod: mods.DEX,
    saves,
    passivePerc: 10 + percBonus,
    attacks: c.attacks || [],
    caster: !!c.caster,
    spell: c.caster ? c.spell || null : null,
    features: c.features || {},
    portrait,
  };
}

function findSlugs() {
  return readdirSync(CHAR_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith("_") && !d.name.startsWith("."))
    .map((d) => d.name)
    .filter((slug) => existsSync(join(CHAR_DIR, slug, `${slug}.html`)))
    .sort();
}

const party = [];
for (const slug of findSlugs()) {
  const html = readFileSync(join(CHAR_DIR, slug, `${slug}.html`), "utf8");
  try {
    const c = extractCharacter(html, slug);
    party.push(toPartyMember(c, slug));
    const m = party[party.length - 1];
    console.log(
      `  ✓ ${m.name.padEnd(22)} ${m.cls.padEnd(34)} AC${m.ac} ${m.maxhp}hp init${m.initMod >= 0 ? "+" : ""}${m.initMod}` +
        (m.caster ? ` · caster (DC ${m.spell?.dc ?? "?"})` : "")
    );
  } catch (e) {
    console.error(`  ✗ ${slug}: ${e.message}`);
    process.exitCode = 1;
  }
}

const header =
  "/* AUTO-GENERATED by modules/the-weeping-grove/build-party.mjs — do not edit by hand.\n" +
  "   Source of truth: characters/<slug>/<slug>.html (each CHARACTER object).\n" +
  "   Regenerate after editing a sheet:  node modules/the-weeping-grove/build-party.mjs\n" +
  "   Loaded by the DM screen as window.WEEPING_GROVE_PARTY. */\n";

writeFileSync(OUT, header + "window.WEEPING_GROVE_PARTY = " + JSON.stringify(party, null, 2) + ";\n");
console.log(`\nWrote ${OUT} (${party.length} party members)`);
