/* ============================================================
   COMBAT COCKPIT — app (readable JSX mirror)
   A live D&D combat screen for The Weeping Grove: initiative,
   HP/damage, death saves, conditions, a tactical token board with
   drag-an-ability-onto-a-target, a dice tray that rolls monster
   attacks from their stat blocks, a flip read-aloud whose back face
   is the FULL DM scene reference, and the candle clock + clue→Key HUD.
   State persists in localStorage.

   ⚠️ NO BUILD STEP. This file is the readable mirror of the app that is
   precompiled to React.createElement inside combat-cockpit.html. Edit BOTH:
   change the inline createElement app in the .html AND this .src.jsx.
   ============================================================ */
const { useState, useEffect, useRef, useCallback } = React;
const E = window.TWGE;
const MON = E.monsters();
const SB = (window.WEEPING_GROVE || window.MODULE || {}).statblocks || {}; // raw stat blocks (monster actions on the board)
const BEATS = E.beats();
const MON_ORDER = ["wolf", "twig", "cultist", "thug", "fanatic", "hag", "mound"].filter((k) => MON[k]);
/* the real party (generated by build-party.mjs) — each PC's attacks, spells & features */
const PARTY = window.WEEPING_GROVE_PARTY || [];
const PARTY_BY_SLUG = {};
PARTY.forEach((p) => { PARTY_BY_SLUG[p.slug] = p; });

const CONDITIONS = ["Prone", "Grappled", "Restrained", "Poisoned", "Frightened", "Concentrating", "Stunned", "Paralyzed", "Blinded"];
const COND_ICON = { Prone: "🛌", Grappled: "✊", Restrained: "🕸", Poisoned: "🤢", Frightened: "😱", Concentrating: "🧠", Stunned: "💫", Paralyzed: "⛓", Blinded: "🙈" };
const condIcon = (cd) => COND_ICON[cd] || "⚑";
/* license-safe creature silhouettes (offline, no MM art) — keyed by statblock `sil` type.
   Rendered faint behind the token label; the letter+number label remains the fallback. */
const SIL_SVG = {
  humanoid: '<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="6.5" r="3.3"/><path d="M5.5 21c0-4 2.9-6.8 6.5-6.8S18.5 17 18.5 21z"/></svg>',
  beast: '<svg viewBox="0 0 24 24" fill="currentColor"><ellipse cx="12" cy="16.5" rx="4.2" ry="3.4"/><circle cx="6.6" cy="12" r="1.9"/><circle cx="17.4" cy="12" r="1.9"/><circle cx="9.2" cy="8.4" r="1.9"/><circle cx="14.8" cy="8.4" r="1.9"/></svg>',
  plant: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.5c-3.2 4.2-6.3 6.4-6.3 10.4a6.3 6.3 0 0 0 12.6 0c0-4-3.1-6.2-6.3-10.4z"/><path d="M11.2 22h1.6v-9h-1.6z"/></svg>',
  fey: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l3.2 5.4H8.8z"/><circle cx="12" cy="10.4" r="2.7"/><path d="M6.6 21c0-3.2 2.4-5.4 5.4-5.4S17.4 17.8 17.4 21z"/></svg>',
};
const tokSil = (c) => { const sb = c.side === "mon" && c.mkey ? SB[c.mkey] : null; return sb && SIL_SVG[sb.sil] ? SIL_SVG[sb.sil] : null; };
/* movement + actions. Grid = 5 ft / cell; the cosmetic grid square is CELL_PX, so a token's
   speed in feet maps to a reach-ring radius of (speed/5)*CELL_PX pixels. PHB diagonals (Chebyshev). */
const CELL_PX = 30;
const ZMIN = 0.5, ZMAX = 3;   // board zoom limits (ephemeral pan/zoom, not persisted)
const ACTIONS = [{ k: "dash", label: "Dash", icon: "⚡" }, { k: "dodge", label: "Dodge", icon: "🛡" }, { k: "disengage", label: "Disengage", icon: "↪" }, { k: "help", label: "Help", icon: "🤝" }, { k: "hide", label: "Hide", icon: "🫥" }];
const ACT_ICON = {}; ACTIONS.forEach((a) => { ACT_ICON[a.k] = a.icon; });
/* action economy (per combatant, per turn). Reset at the start of that combatant's turn. */
const emptyEcon = () => ({ action: false, bonus: false, reaction: false });
const ECON = [{ k: "action", label: "A", title: "Action" }, { k: "bonus", label: "B", title: "Bonus action" }, { k: "reaction", label: "R", title: "Reaction" }];
/* ---- spell-slot / innate-use economy, seeded from the data (single source of truth) ----
   PCs: spell.slots {lvl:count}. Monsters: parse the Spellcasting/Innate trait —
   "Nth (M slots)" = leveled slots, "N/day [each]" = innate uses per spell,
   "At will" / cantrips = unlimited (untracked). */
function pcCasting(pc) {
  const slots = {}; const sp = pc && pc.spell;
  if (sp && sp.slots) Object.keys(sp.slots).forEach((k) => { const lv = +k; if (lv >= 1) slots[lv] = sp.slots[k]; });
  return { slots, innate: {} };
}
function monsterCasting(sb) {
  const slots = {}, innate = {};
  ((sb && sb.traits) || []).forEach((tr) => {
    if (!/spellcasting/i.test(tr.n || "")) return;
    const raw = String(tr.t || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
    let m; const slotRe = /(\d+)(?:st|nd|rd|th)\s*\((\d+)\s*slots?\)/gi;
    while ((m = slotRe.exec(raw))) slots[+m[1]] = +m[2];
    const innRe = /(\d+)\s*\/\s*day(?:\s+each)?\s*:\s*([^;.]+)/gi;
    while ((m = innRe.exec(raw))) { const uses = +m[1]; m[2].split(",").forEach((nm) => { const n = nm.trim().replace(/[.;]+$/, "").toLowerCase(); if (n) innate[n] = uses; }); }
  });
  return { slots, innate };
}
function slotsFor(c) {
  if (c.side === "pc") return pcCasting(PARTY_BY_SLUG[c.slug]);
  const sb = SB[c.mkey]; return sb ? monsterCasting(sb) : { slots: {}, innate: {} };
}
const hasCasting = (c) => !!(c && ((c.slots && Object.keys(c.slots).length) || (c.innate && Object.keys(c.innate).length)));
/* what a chip consumes when it resolves: {kind:"slot",lvl} | {kind:"innate",key} | null (cantrip/at-will/weapon) */
function spendOf(ability) {
  if (!ability) return null;
  if (typeof ability.slotLevel === "number" && ability.slotLevel >= 1) return { kind: "slot", lvl: ability.slotLevel };
  const lv = ability.level;
  if (typeof lv === "string") {
    const sm = lv.match(/^(\d+)(?:st|nd|rd|th)$/i);
    if (sm) return { kind: "slot", lvl: +sm[1] };
    if (/\/\s*day/i.test(lv)) return { kind: "innate", key: (ability.note || ability.name || "").toLowerCase().trim() };
  }
  return null;
}
const speedOf = (c) => { const raw = c.side === "pc" ? (PARTY_BY_SLUG[c.slug] || {}).speed : (SB[c.mkey] || {}).speed; return E.toNum(raw, 0) || 30; };
/* Chebyshev distance in feet between two board points (untransformed world px) */
function ftBetween(x1, y1, x2, y2) { return Math.round(Math.max(Math.abs(x2 - x1), Math.abs(y2 - y1)) / CELL_PX) * 5; }
const CLUE_NAMES = ["Victims came to TAKE", "It's the wood, not a beast", "The cult drives it", "Mother Sere's rite", "The Guardian grieves"];

const LS = "twg-cockpit-v2";
const uid = () => Math.random().toString(36).slice(2, 9);
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));

const DEFAULT = {
  round: 0, turnId: null,
  combatants: [],
  clues: [false, false, false, false, false],
  beat: Math.max(0, BEATS.findIndex((b) => b.id === "scene1")),
  roll: "me",
  view: "read",          // center view: "read" (read-aloud / DM notes) | "board" (token board)
  selId: null,           // selected token (board detail panel)
  version: "A",          // Showdown A/B for the scene reference
  versionTouched: false, // DM manually picked a version (else it follows the Key)
  fightSig: null,        // "<beat>:<ver>" of the scene whose enemies are currently set up (auto-load guard)
  sceneImg: {},          // { [sceneId]: localPath } — DM-supplied atmosphere image per scene (offline)
  lootGiven: {},         // { [itemId]: true } — scene-reward items the DM has handed to the party
};
function load() {
  try {
    const s = JSON.parse(localStorage.getItem(LS));
    if (s && s.combatants) {
      const merged = { ...DEFAULT, ...s, combatants: withPositions(s.combatants) };
      if (!("view" in s)) merged.view = merged.combatants.length ? "board" : "read"; // land on the map mid-fight
      if (!("fightSig" in s)) {
        // upgraded save: pin fightSig to the current scene if monsters are already present
        // so we don't disturb a fight the DM was already running.
        const ev = merged.versionTouched ? merged.version : (merged.clues.filter(Boolean).length >= 3 ? "B" : "A");
        merged.fightSig = merged.combatants.some((c) => c.side === "mon") ? merged.beat + ":" + ev : null;
      }
      return merged;
    }
  } catch (e) {}
  return { ...DEFAULT };
}

/* initiative sort: a manual `seq` override (baked by drag/↑↓ reorder) wins when present,
   so the DM's order sticks and nextTurn follows the displayed list; otherwise fall back to
   init desc → dex mod → name. Sparse seq is fine — un-seq'd combatants sink below seq'd ones. */
function sortInit(list) {
  return [...list].sort((a, b) => {
    const aS = typeof a.seq === "number", bS = typeof b.seq === "number";
    if (aS && bS) return a.seq - b.seq;
    if (aS !== bS) return aS ? -1 : 1;
    return (b.init - a.init) || (b.dexmod - a.dexmod) || a.name.localeCompare(b.name);
  });
}

/* ---- board placement: PCs along the bottom band, monsters along the top, spread out.
   Positions are fractions [0..1] of the board so they survive reload/resize. ---- */
function placeDefault(side, i) {
  const col = i % 6, row = Math.floor(i / 6);
  const x = 0.1 + col * 0.15 + (row % 2) * 0.06;
  const y = side === "pc" ? 0.84 - row * 0.13 : 0.16 + row * 0.13;
  return { x: clamp(x, 0.05, 0.95), y: clamp(y, 0.05, 0.95) };
}
/* normalize each combatant: back-fill x,y (old saves + fresh preloads/adds) AND the v2.2
   action/slot economy (econ/slots/innate). Idempotent — never clobbers existing values, so a
   running fight's spent slots/positions survive a reload. `seq` stays sparse (set only on reorder). */
function withPositions(list) {
  const idx = { pc: 0, mon: 0 };
  return (list || []).map((c) => {
    const side = c.side === "pc" ? "pc" : "mon";
    const i = idx[side]++;
    const out = (typeof c.x === "number" && typeof c.y === "number") ? { ...c } : { ...c, ...placeDefault(side, i) };
    if (!out.econ) out.econ = emptyEcon();
    if (!out.slots || !out.innate) { const sd = slotsFor(out); if (!out.slots) out.slots = sd.slots; if (!out.innate) out.innate = sd.innate; }
    return out;
  });
}

/* ---- build combatants from the party / monster keys (preload + "add party") ---- */
function pcCombatant(p) {
  const sd = pcCasting(p);
  return {
    id: uid(), side: "pc", mkey: null, slug: p.slug, name: p.name || "PC",
    init: E.rollDie(20) + (p.initMod || 0),
    ac: p.ac != null ? p.ac : 14, maxhp: p.maxhp || 1, hp: p.maxhp || 1,
    dexmod: p.initMod || 0, conds: [], deaths: { s: 0, f: 0 },
    econ: emptyEcon(), slots: sd.slots, innate: sd.innate,
  };
}
function monCombatant(key, i) {
  const m = MON[key];
  const sd = monsterCasting(SB[key] || {});
  return {
    id: uid(), side: "mon", mkey: key, name: m.name + " " + (i + 1),
    init: E.rollDie(20) + m.dexmod, ac: m.ac, maxhp: m.maxhp, hp: m.maxhp,
    dexmod: m.dexmod, conds: [], deaths: { s: 0, f: 0 },
    econ: emptyEcon(), slots: sd.slots, innate: sd.innate,
  };
}
/* {enemies:[{key,count}], addParty} (from the DM screen's ⚔ Combat) → a fresh, pre-initiative
   roster: the whole party + the scene's monsters, placed on the board, ready to roll. */
function buildLoadState(payload) {
  const combatants = [];
  if (payload.addParty) PARTY.forEach((p) => combatants.push(pcCombatant(p)));
  (payload.enemies || []).forEach(({ key, count }) => {
    if (!MON[key]) return;
    for (let i = 0; i < (count || 1); i++) combatants.push(monCombatant(key, i));
  });
  return { combatants: withPositions(combatants), round: 0, turnId: null, view: "board", selId: null };
}

/* ---- PC abilities (reference for the DM; players roll their own) ---- */
function slotsTxt(sp) {
  if (!sp || !sp.slots) return "";
  const parts = Object.keys(sp.slots).map((k) => sp.slots[k] + "×L" + k);
  return parts.length ? " · slots " + parts.join(", ") : "";
}
function PCDetail({ pc }) {
  if (!pc) return null;
  const sp = pc.spell;
  const spells = sp ? [].concat(sp.cantrips || []).concat(sp.known || sp.prepared || []) : [];
  const feats = []
    .concat((pc.features && pc.features.race) || [])
    .concat((pc.features && pc.features.class) || [])
    .concat((pc.features && pc.features.background) || []);
  return (
    <div className="ck-pcd">
      <div className="ck-pcd-line">{[pc.race, pc.cls || pc.class, pc.background].filter(Boolean).join(" · ")}</div>
      {pc.attacks && pc.attacks.length > 0 && (
        <div className="ck-pcd-sec">
          <h6>⚔ Attacks</h6>
          {pc.attacks.map((a, i) => (
            <div key={i} className="ck-atk">
              <div className="ck-atk-top"><b>{a.name}</b>
                <span className="ck-atk-nums">{[a.bonus, a.dmg, a.range, a.use].filter(Boolean).join(" · ")}</span></div>
              {a.note && <div className="ck-atk-note">{a.note}</div>}
            </div>
          ))}
        </div>
      )}
      {sp && (
        <div className="ck-pcd-sec">
          <h6>✦ Spells<span className="ck-sp-dc">{" save DC " + sp.dc + " · atk " + sp.atk + slotsTxt(sp)}</span></h6>
          {spells.map((s, i) => (
            <div key={i} className="ck-sp">
              <div className="ck-sp-top"><b>{s.name}</b>
                <span className="ck-sp-meta">{(s.lvl === "cantrip" ? "cantrip" : "L" + s.lvl) + " · " + s.castTime + (s.concentration ? " · conc" : "")}</span>
                {s.roll && s.roll !== "No roll" && <span className="ck-sp-roll">{s.roll}</span>}</div>
              <div className="ck-sp-eff">{s.effect}</div>
              {s.when && <div className="ck-sp-when">{"▸ " + s.when}</div>}
            </div>
          ))}
        </div>
      )}
      {feats.length > 0 && (
        <div className="ck-pcd-sec">
          <h6>★ Features</h6>
          {feats.map((f, i) => (
            <div key={i} className="ck-feat">
              <b>{f.n}</b>{f.use && <span className="ck-feat-use">{" " + f.use}</span>}
              <div className="ck-feat-t">{f.t}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

/* ============================ ROOT ============================ */
function Cockpit() {
  const [st, setSt] = useState(load);
  useEffect(() => { localStorage.setItem(LS, JSON.stringify(st)); }, [st]);
  const up = (patch) => setSt((s) => ({ ...s, ...(typeof patch === "function" ? patch(s) : patch) }));

  const sorted = sortInit(st.combatants);
  const fighting = st.round > 0 && sorted.length > 0;
  const activeId = fighting ? st.turnId : null;
  const active = sorted.find((c) => c.id === activeId) || null;

  /* shared combat log (board drops + dice tray write here) — in-memory, not persisted */
  const [log, setLog] = useState([]);
  const pushLog = useCallback((entry) => setLog((l) => [{ id: uid(), ...entry }, ...l].slice(0, 24)), []);
  const [lootOpen, setLootOpen] = useState(false);   // loot/rewards overlay (modal, not persisted)

  /* Showdown version follows the Key (3+ clues) until the DM picks one manually */
  const cluesLit = st.clues.filter(Boolean).length;
  const effVersion = st.versionTouched ? st.version : (cluesLit >= 3 ? "B" : "A");
  const setVersion = (v) => up({ version: v, versionTouched: true });

  /* ---- combatant ops ---- */
  const addMonster = (key) => {
    const m = MON[key]; if (!m) return;
    const sameCount = st.combatants.filter((c) => c.mkey === key).length;
    const init = E.rollDie(20) + m.dexmod;
    const c = {
      id: uid(), side: "mon", mkey: key, name: m.name + " " + (sameCount + 1),
      init, ac: m.ac, maxhp: m.maxhp, hp: m.maxhp, dexmod: m.dexmod,
      conds: [], deaths: { s: 0, f: 0 },
    };
    up((s) => ({ combatants: withPositions([...s.combatants, c]), turnId: s.turnId || (s.round > 0 ? c.id : null) }));
  };
  const addPC = (pc) => {
    const c = {
      id: uid(), side: "pc", mkey: null, name: pc.name || "PC",
      init: pc.init ?? (E.rollDie(20)), ac: pc.ac ?? 14, maxhp: pc.maxhp ?? 24, hp: pc.maxhp ?? 24,
      dexmod: pc.dexmod ?? 1, conds: [], deaths: { s: 0, f: 0 },
    };
    up((s) => ({ combatants: withPositions([...s.combatants, c]) }));
  };
  const patchC = (id, patch) => up((s) => ({
    combatants: s.combatants.map((c) => (c.id === id ? { ...c, ...(typeof patch === "function" ? patch(c) : patch) } : c)),
  }));
  const removeC = (id) => up((s) => {
    const rest = s.combatants.filter((c) => c.id !== id);
    let turnId = s.turnId;
    if (s.turnId === id) { const so = sortInit(rest); turnId = so.length ? so[0].id : null; }
    return { combatants: rest, turnId, selId: s.selId === id ? null : s.selId };
  });
  const damage = (id, amt) => patchC(id, (c) => {
    const hp = clamp(c.hp - amt, -999, c.maxhp);
    const next = { hp };
    if (hp > 0) next.deaths = { s: 0, f: 0 };
    return next;
  });
  const heal = (id, amt) => patchC(id, (c) => ({ hp: clamp(c.hp + amt, -999, c.maxhp), deaths: c.hp + amt > 0 ? { s: 0, f: 0 } : c.deaths }));

  /* ---- turn flow ---- (econ resets at the start of whoever's turn it becomes) */
  const resetEconFor = (list, id) => list.map((c) => (c.id === id ? { ...c, econ: emptyEcon() } : c));
  const setTurn = (id) => up((s) => ({ turnId: id, combatants: resetEconFor(s.combatants, id) })); // manual: pick the active turn, keep the round
  const startFight = () => {
    const so = sortInit(st.combatants);
    if (!so.length) return;
    up((s) => ({ round: 1, turnId: so[0].id, combatants: resetEconFor(s.combatants, so[0].id) }));
  };
  const endFight = () => up({ round: 0, turnId: null });
  const nextTurn = () => {
    const so = sortInit(st.combatants);
    if (!so.length) return;
    const i = so.findIndex((c) => c.id === st.turnId);
    const wrap = i !== -1 && i + 1 >= so.length;
    const nextId = (i === -1 || i + 1 >= so.length) ? so[0].id : so[i + 1].id;
    up((s) => ({ turnId: nextId, round: wrap ? s.round + 1 : s.round, combatants: resetEconFor(s.combatants, nextId) }));
  };
  /* manual initiative reorder (↑/↓): move within the displayed order, then bake `seq` into ALL
     combatants so the new order sticks and nextTurn follows it. */
  const reorder = (id, dir) => up((s) => {
    const ord = sortInit(s.combatants);
    const i = ord.findIndex((c) => c.id === id), j = i + dir;
    if (i < 0 || j < 0 || j >= ord.length) return {};
    const arr = ord.slice(); arr.splice(j, 0, arr.splice(i, 1)[0]);
    const seqOf = {}; arr.forEach((c, k) => { seqOf[c.id] = k; });
    return { combatants: s.combatants.map((c) => ({ ...c, seq: seqOf[c.id] })) };
  });

  const resetAll = () => { if (confirm("Clear the whole fight and trackers?")) setSt({ ...DEFAULT }); };

  /* ---- preload from the DM screen (⚔ Combat) + announce readiness to the shell ---- */
  const stRef = useRef(st);
  stRef.current = st;
  useEffect(() => {
    try { window.parent.postMessage({ type: "twg-cockpit-ready" }, "*"); } catch (e) {}
    const onMsg = (e) => {
      const d = e && e.data;
      if (!d || d.type !== "twg-combat-load") return;
      if (stRef.current.round > 0 && !confirm("Load this scene's fight? It replaces the current combatants.")) return;
      setSt((s) => ({ ...s, ...buildLoadState(d) }));
    };
    window.addEventListener("message", onMsg);
    return () => window.removeEventListener("message", onMsg);
  }, []);
  // Add the whole party (skips PCs already in), e.g. when the cockpit is opened directly.
  const addParty = () => up((s) => {
    const have = new Set(s.combatants.filter((c) => c.side === "pc").map((c) => c.slug));
    const add = PARTY.filter((p) => !have.has(p.slug)).map(pcCombatant);
    return { combatants: withPositions([...s.combatants, ...add]) };
  });

  /* ---- party-wide rests (PCs only). Long = full restore; Short = 5e-style: action economy
     clears, Warlock pact slots return, and a DM-entered heal is applied to conscious PCs. ---- */
  const longRest = () => {
    if (!confirm("Long rest the party? Restores every PC to full HP and all spell slots, and clears action economy + death saves.")) return;
    up((s) => ({ combatants: s.combatants.map((c) => {
      if (c.side !== "pc") return c;
      const sd = slotsFor(c);
      return { ...c, hp: c.maxhp, slots: sd.slots, innate: sd.innate, econ: emptyEcon(), deaths: { s: 0, f: 0 } };
    }) }));
    pushLog({ kind: "roll", html: "🌙 <b>Long rest</b> — party restored to full HP &amp; all spell slots" });
  };
  const shortRest = () => {
    const raw = window.prompt("Short rest — HP to restore to each conscious PC? (blank = none)", "");
    if (raw === null) return;
    const heal = Math.max(0, parseInt(raw, 10) || 0);
    let warlocks = 0;
    up((s) => ({ combatants: s.combatants.map((c) => {
      if (c.side !== "pc") return c;
      const pc = PARTY_BY_SLUG[c.slug];
      const next = { ...c, econ: emptyEcon() };
      if (pc && /warlock/i.test(pc.cls || "")) { next.slots = slotsFor(c).slots; warlocks++; }   // Pact Magic recovers on a short rest
      if (heal && c.hp > 0) next.hp = clamp(c.hp + heal, -999, c.maxhp);
      return next;
    }) }));
    pushLog({ kind: "roll", html: "🛌 <b>Short rest</b> — action economy reset" + (heal ? " · +" + heal + " HP to each conscious PC" : "") + (warlocks ? " · Warlock pact slots restored" : "") });
  };
  const openParty = () => { try { window.open("../../../characters/index.html#cockpit", "_blank"); } catch (e) {} };
  const toggleLoot = (id) => up((s) => ({ lootGiven: { ...(s.lootGiven || {}), [id]: !(s.lootGiven && s.lootGiven[id]) } }));

  /* ---- each scene sets up its own fight: derive enemies from the scene body, keep the
     party (hp/conditions/death saves/positions), replace the previous scene's monsters.
     Confirm before discarding a fight that is in progress with living enemies. ---- */
  const maybeLoadFight = () => {
    const s = stRef.current;
    const beat = BEATS[s.beat];
    const ver = s.versionTouched ? s.version : (s.clues.filter(Boolean).length >= 3 ? "B" : "A");
    const sig = s.beat + ":" + ver;
    if (s.fightSig === sig) return;
    const enemies = E.sceneEnemies(beat, ver);
    if (!enemies.length) { up({ fightSig: sig }); return; }  // non-combat scene: leave the board as is
    const aliveMons = s.combatants.some((c) => c.side === "mon" && c.hp > 0);
    if (s.round > 0 && aliveMons &&
        !window.confirm("Set up “" + (beat ? beat.name : "this") + "” fight? Replaces the current monsters (party kept).")) {
      up({ fightSig: sig }); return;                          // DM declined — keep the current fight, don't re-prompt
    }
    const pcs = s.combatants.filter((c) => c.side === "pc");
    const mons = [];
    enemies.forEach(({ key, count }) => { for (let i = 0; i < count; i++) mons.push(monCombatant(key, i)); });
    up({ combatants: withPositions([...pcs, ...mons]), fightSig: sig });
  };
  useEffect(() => { maybeLoadFight(); }, [st.beat, effVersion]);

  return (
    <div className="ck">
      <Header round={st.round} fighting={fighting} active={active}
        onStart={startFight} onNext={nextTurn} onEnd={endFight} onReset={resetAll}
        onParty={openParty} onLoot={() => setLootOpen(true)} onShortRest={shortRest} onLongRest={longRest} />
      <div className="ck-main">
        <Initiative sorted={sorted} activeId={activeId} fighting={fighting} rollMode={st.roll}
          onDamage={damage} onHeal={heal} onRemove={removeC} onPatch={patchC} onSetTurn={setTurn} onReorder={reorder} />
        <CenterColumn active={active} st={st} up={up} onDamage={damage} onHeal={heal} onPatch={patchC}
          onRemove={removeC} sorted={sorted} version={effVersion} onVersion={setVersion} log={log} onLog={pushLog} onSetTurn={setTurn} />
        <HUD st={st} up={up} onAddMonster={addMonster} onAddPC={addPC} onAddParty={addParty} />
      </div>
      {lootOpen && <LootPanel beat={st.beat} lootGiven={st.lootGiven || {}} onToggle={toggleLoot} onClose={() => setLootOpen(false)} />}
    </div>
  );
}

/* ============================ HEADER ============================ */
function Header({ round, fighting, active, onStart, onNext, onEnd, onReset, onParty, onLoot, onShortRest, onLongRest }) {
  return (
    <header className="ck-head">
      <div className="ck-title">🌲 Weeping Grove <span>Combat Cockpit</span></div>
      <div className="ck-tools">
        <button className="ck-ghost ck-tool" onClick={onParty} title="Open the player Party roster in a new tab">🎭 The Party →</button>
        <button className="ck-ghost ck-tool" onClick={onLoot} title="Scene rewards / loot to hand out">🎁 Loot</button>
        <button className="ck-ghost ck-tool" onClick={onShortRest} title="Short rest — reset action economy, restore Warlock pact slots, heal each conscious PC">🛌 Short</button>
        <button className="ck-ghost ck-tool" onClick={onLongRest} title="Long rest — restore all PCs to full HP + all spell slots">🌙 Long</button>
      </div>
      <div className="ck-turnbox">
        {fighting ? (
          <>
            <span className="ck-round">⚔ Round {round}</span>
            <span className="ck-active">{active ? active.name : "—"}</span>
            <button className="ck-next" onClick={onNext}>Next turn ⏭</button>
            <button className="ck-ghost" onClick={onEnd}>End</button>
          </>
        ) : (
          <button className="ck-start" onClick={onStart}>▶ Roll for initiative</button>
        )}
        <button className="ck-ghost sm" onClick={onReset} title="Clear everything">⟲</button>
      </div>
    </header>
  );
}

/* ============================ INITIATIVE ============================ */
function Initiative({ sorted, activeId, fighting, rollMode, onDamage, onHeal, onRemove, onPatch, onSetTurn, onReorder }) {
  return (
    <section className="ck-panel ck-init">
      <h2>Initiative {sorted.length > 0 && <span className="ck-count">{sorted.length}</span>}</h2>
      <div className="ck-initlist">
        {sorted.length === 0 && <p className="ck-empty">Add fighters from the roster on the right, then hit <b>Roll for initiative</b>.</p>}
        {sorted.map((c, i) => (
          <InitRow key={c.id} c={c} active={c.id === activeId} fighting={fighting} rollMode={rollMode}
            idx={i} total={sorted.length} onSetTurn={onSetTurn} onReorder={onReorder}
            onDamage={onDamage} onHeal={onHeal} onRemove={onRemove} onPatch={onPatch} />
        ))}
      </div>
    </section>
  );
}

function InitRow({ c, active, fighting, rollMode, idx, total, onSetTurn, onReorder, onDamage, onHeal, onRemove, onPatch }) {
  const [amt, setAmt] = useState("");
  const [open, setOpen] = useState(false);
  const [dval, setDval] = useState("");
  const [showAbil, setShowAbil] = useState(false);
  const down = c.hp <= 0;
  const pc = c.side === "pc" ? PARTY_BY_SLUG[c.slug] : null;
  const pct = clamp((c.hp / c.maxhp) * 100, 0, 100);
  const band = c.hp <= 0 ? "crit" : pct <= 25 ? "crit" : pct <= 50 ? "low" : "ok";
  const apply = (sign) => {
    const n = parseInt(amt, 10); if (isNaN(n) || n === 0) return;
    sign > 0 ? onHeal(c.id, n) : onDamage(c.id, n);
    setAmt("");
  };
  const applyDeath = (d) => {
    if (isNaN(d) || d < 1 || d > 20) return;
    if (d === 20) { onHeal(c.id, 1); return; }
    onPatch(c.id, (cc) => {
      const ds = { ...cc.deaths };
      if (d === 1) ds.f = Math.min(3, ds.f + 2);
      else if (d >= 10) ds.s = Math.min(3, ds.s + 1);
      else ds.f = Math.min(3, ds.f + 1);
      return { deaths: ds };
    });
  };
  return (
    <div className={"ck-row " + c.side + (active ? " active" : "") + (down ? " down" : "")}>
      <div className="ck-rmain">
        <input className="ck-initin" title="initiative — editable" inputMode="numeric" value={c.init}
          onChange={(e) => onPatch(c.id, { init: parseInt(e.target.value, 10) || 0 })} />
        <button className="ck-name" title="make this the current turn" onClick={() => onSetTurn && onSetTurn(c.id)}>
          <span className="ck-marker">{active ? "▶" : ""}</span>{c.name}</button>
        <span className="ck-ac" title="armor class">🛡{c.ac}</span>
        <span className="ck-reorder">
          <button className="ck-seqbtn" title="move earlier in initiative" disabled={idx === 0} onClick={() => onReorder && onReorder(c.id, -1)}>↑</button>
          <button className="ck-seqbtn" title="move later in initiative" disabled={idx === total - 1} onClick={() => onReorder && onReorder(c.id, 1)}>↓</button>
        </span>
        <button className="ck-x" onClick={() => onRemove(c.id)} title="remove">✕</button>
      </div>
      <div className="ck-hpwrap">
        <div className="ck-hpbar"><i className={band} style={{ width: pct + "%" }}></i></div>
        <span className="ck-hpnum">{c.hp}<span>/{c.maxhp}</span></span>
        <input className="ck-amt" inputMode="numeric" placeholder="#" value={amt}
          onChange={(e) => setAmt(e.target.value.replace(/[^0-9]/g, ""))}
          onKeyDown={(e) => { if (e.key === "Enter") apply(-1); }} />
        <button className="ck-dmg" onClick={() => apply(-1)} title="damage">−</button>
        <button className="ck-heal" onClick={() => apply(1)} title="heal">+</button>
      </div>
      {down && c.side === "pc" && (
        <div className="ck-death">
          <span className="ck-dlbl">Death saves</span>
          <span className="pips s">{[0, 1, 2].map((i) => <i key={i} className={i < c.deaths.s ? "on" : ""}></i>)}</span>
          <span className="pips f">{[0, 1, 2].map((i) => <i key={i} className={i < c.deaths.f ? "on" : ""}></i>)}</span>
          {rollMode === "me" ? (
            <span className="ck-dmanual">
              <input className="ck-d20in sm" inputMode="numeric" placeholder="d20" value={dval}
                onChange={(e) => setDval(e.target.value.replace(/[^0-9]/g, ""))}
                onKeyDown={(e) => { if (e.key === "Enter") { applyDeath(parseInt(dval, 10)); setDval(""); } }} />
              <button className="ck-droll" onClick={() => { applyDeath(parseInt(dval, 10)); setDval(""); }}>ok</button>
            </span>
          ) : (
            <button className="ck-droll" onClick={() => applyDeath(E.rollDie(20))}>roll d20</button>
          )}
          {c.deaths.f >= 3 && <span className="ck-dead">DEAD</span>}
          {c.deaths.s >= 3 && <span className="ck-stable">STABLE</span>}
        </div>
      )}
      {pc && (
        <div className="ck-pcabil">
          <button className="ck-abilbtn" onClick={() => setShowAbil((o) => !o)}>
            {showAbil ? "▾ abilities & spells" : "▸ abilities & spells"}
          </button>
          {showAbil && <PCDetail pc={pc} />}
        </div>
      )}
      <div className="ck-conds">
        {c.conds.map((cd) => (
          <button key={cd} className="ck-cond" onClick={() => onPatch(c.id, (cc) => ({ conds: cc.conds.filter((x) => x !== cd) }))}>{cd} ✕</button>
        ))}
        <button className="ck-condadd" onClick={() => setOpen((o) => !o)}>+ condition</button>
        {open && (
          <div className="ck-condmenu" onMouseLeave={() => setOpen(false)}>
            {CONDITIONS.filter((cd) => !c.conds.includes(cd)).map((cd) => (
              <button key={cd} onClick={() => { onPatch(c.id, (cc) => ({ conds: [...cc.conds, cd] })); setOpen(false); }}>{cd}</button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

/* ============================ CENTER: SCENE/BOARD + DICE ============================ */
/* scene-reference helpers — port of the DM screen's collapsify + version visibility, run
   imperatively on the injected scene HTML (native <details> + the ported .ck-scene styles). */
function collapsify(root) {
  const candidates = [...root.querySelectorAll(".zone, .callout, .runfight")];
  let firstSec = null;
  candidates.forEach((el) => {
    if (!el.isConnected) return;
    if (el.parentElement && el.parentElement.closest(".zone, .callout, .runfight")) return; // nested -> leave inside parent
    const isCallout = el.classList.contains("callout");
    const isFight = el.classList.contains("runfight");
    let title = null;
    const hh = el.querySelector(":scope > h4");
    if (hh) { title = hh.innerHTML; hh.remove(); }
    else { const bb = el.querySelector(":scope > b"); if (bb) { title = bb.innerHTML; bb.remove(); } }
    if (!title) title = isFight ? "🎬 Run the fight" : (isCallout ? "⚠ Note" : "Details");
    const det = document.createElement("details");
    det.className = "beat-sec";
    if (el.classList.contains("secret")) det.classList.add("is-secret");
    if (el.classList.contains("danger")) det.classList.add("is-danger");
    if (isFight) det.classList.add("is-fight");
    const sum = document.createElement("summary");
    sum.innerHTML = '<span class="sum-title">' + title + "</span>";
    det.appendChild(sum);
    const body = document.createElement("div"); body.className = "sec-body";
    while (el.firstChild) body.appendChild(el.firstChild);
    det.appendChild(body);
    el.replaceWith(det);
    if (!firstSec) firstSec = det;
  });
  if (firstSec) {
    const tools = document.createElement("div");
    tools.className = "sec-tools";
    tools.innerHTML = '<button data-secexpand type="button">⊕ Expand all</button><button data-seccollapse type="button">⊖ Collapse all</button>';
    firstSec.parentNode.insertBefore(tools, firstSec);
  }
}
function applyVer(root, version) {
  root.querySelectorAll(".ver-block[data-verblock]").forEach((el) => el.classList.toggle("show", el.dataset.verblock === version));
}

function CenterColumn({ active, st, up, onDamage, onHeal, onPatch, onRemove, sorted, version, onVersion, log, onLog, onSetTurn }) {
  const [flip, setFlip] = useState(false);
  const view = st.view || "read";
  const b = BEATS[st.beat];
  const go = (d) => { setFlip(false); up({ beat: clamp(st.beat + d, 0, BEATS.length - 1) }); };
  const showVer = !!(b && b.hasVer);
  return (
    <section className="ck-center">
      <div className="ck-ra">
        <div className="ck-ra-head">
          <button className="ck-ra-nav" onClick={() => go(-1)} disabled={st.beat === 0}>◀</button>
          <span className="ck-ra-beat">{b ? (b.icon + " " + b.name) : "—"}</span>
          <button className="ck-ra-nav" onClick={() => go(1)} disabled={st.beat === BEATS.length - 1}>▶</button>
          <div className="ck-seg ck-viewseg">
            <button className={view === "read" ? "on" : ""} onClick={() => up({ view: "read" })}>📖 Read</button>
            <button className={view === "board" ? "on" : ""} onClick={() => up({ view: "board" })}>🗺 Board</button>
          </div>
          {view === "read" && showVer && flip && (
            <div className="ck-seg ck-verseg">
              <button className={version === "A" ? "on" : ""} onClick={() => onVersion("A")}>Ver A</button>
              <button className={version === "B" ? "on" : ""} onClick={() => onVersion("B")}>Ver B</button>
            </div>
          )}
          {view === "read" && (
            <button className={"ck-flip" + (flip ? " on" : "")} onClick={() => setFlip((f) => !f)}>
              ⟳ {flip ? "Read-aloud" : "DM notes"}
            </button>
          )}
        </div>
        {view === "board"
          ? <BoardView sorted={sorted} active={active} st={st} up={up} onDamage={onDamage} onHeal={onHeal} onPatch={onPatch} onRemove={onRemove} onLog={onLog} version={version} onSetTurn={onSetTurn} />
          : <ReadAloud beat={st.beat} flip={flip} version={version}
              /* default-probe img/scenes/<sceneId>.png unless the DM set an explicit path (incl. "" = hidden) */
              img={b ? ((st.sceneImg && (b.id in st.sceneImg)) ? st.sceneImg[b.id] : ("img/scenes/" + b.id + ".png")) : ""}
              onImg={(p) => b && up((s) => ({ sceneImg: { ...s.sceneImg, [b.id]: p } }))} />}
      </div>
      <DiceTray active={active} sorted={sorted} onDamage={onDamage} rollMode={st.roll} setRollMode={(m) => up({ roll: m })} log={log} onLog={onLog} />
    </section>
  );
}

/* Read-aloud card: front = scripted read-aloud; back (flip) = the FULL DM scene reference
   (expanded stat blocks + collapsible zones/checks/run-the-fight, Showdown A/B aware). */
function ReadAloud({ beat, flip, version, img, onImg }) {
  const b = BEATS[beat];
  const sceneRef = useRef(null);
  useEffect(() => {
    if (!flip) return;                       // only build the scene when the notes face shows
    const el = sceneRef.current; if (!el || !b) return;
    el.innerHTML = E.expandSB(b.body || "");
    collapsify(el);
    applyVer(el, version);
    const onClick = (ev) => {
      const t = ev.target; if (!t || !t.closest) return;
      if (t.closest("[data-secexpand]")) el.querySelectorAll("details.beat-sec").forEach((d) => d.open = true);
      else if (t.closest("[data-seccollapse]")) el.querySelectorAll("details.beat-sec").forEach((d) => d.open = false);
    };
    el.addEventListener("click", onClick);
    return () => el.removeEventListener("click", onClick);
  }, [beat, flip, version, b]);
  if (!b) return null;
  return (
    <div className={"ck-card" + (flip ? " flip" : "")}>
      <div className="ck-face ck-front">
        {img ? <img className="ck-ra-img" src={img} alt="" onError={(e) => { e.target.style.display = "none"; }} /> : null}
        {b.ra.length ? b.ra.map((r, i) => (
          <div key={i} className="ck-ra-block">
            <span className="ck-ra-eyebrow">📖 {r.label}</span>
            <div className="ck-ra-text" dangerouslySetInnerHTML={{ __html: r.html }} />
          </div>
        )) : <p className="ck-ra-text" style={{ opacity: .6 }}>No scripted read-aloud — narrate freely.</p>}
        <div className="ck-ra-imgrow">
          <span className="ck-ra-imglbl" title="local atmosphere image for this scene">🖼</span>
          <input className="ck-ra-imgin" placeholder="scene image path — e.g. img/scenes/scene1.jpg" value={img} onChange={(e) => onImg(e.target.value)} />
          {img ? <button className="ck-ra-imgx" title="clear" onClick={() => onImg("")}>✕</button> : null}
        </div>
      </div>
      <div className="ck-face ck-back">
        <span className="ck-ra-eyebrow secret">🔒 DM only — keep secret</span>
        <div className="ck-scene" ref={sceneRef} />
      </div>
    </div>
  );
}

function DiceTray({ active, sorted, onDamage, rollMode, setRollMode, log, onLog }) {
  const [mod, setMod] = useState(0);
  const [mode, setMode] = useState("normal");
  const [target, setTarget] = useState("");
  const [pending, setPending] = useState(null); // {dmg, label}
  const [tgtId, setTgtId] = useState("");
  const [d20v, setD20v] = useState("");  // manual natural d20
  const [dmgv, setDmgv] = useState("");  // manual damage total
  const manual = rollMode === "me";
  const pcs = sorted.filter((c) => c.side === "pc");
  const push = onLog; // shared combat log (lifted to Cockpit root; board drops write here too)
  const readD20 = () => { const n = parseInt(d20v, 10); return isNaN(n) ? null : clamp(n, 1, 20); };

  const rollCheck = () => {
    let die, dice;
    if (manual) { die = readD20(); if (die == null) return; dice = [die]; }
    else { const r = E.d20(0, mode); die = r.die; dice = r.dice; }
    const total = die + mod;
    const tgt = parseInt(target, 10);
    let verdict = "", kind = "roll";
    if (!isNaN(tgt)) { const hit = total >= tgt || die === 20; verdict = hit ? ` — HIT (vs ${tgt})` : ` — miss (vs ${tgt})`; kind = hit ? "hit" : "miss"; }
    if (die === 20) { verdict = " — NAT 20!"; kind = "hit"; }
    if (die === 1) { verdict = " — NAT 1"; kind = "miss"; }
    const dtxt = dice.length > 1 ? ` [${dice.join("/")}→${die}]` : ` [${die}]`;
    push({ kind, html: `d20${mod ? (mod > 0 ? "+" + mod : mod) : ""}${dtxt} = <b>${total}</b>${verdict}` });
    if (manual) setD20v("");
  };
  const rollFree = (s) => { const d = E.rollDie(s); push({ kind: "roll", html: `d${s} = <b>${d}</b>` }); };

  const rollAttack = (atk) => {
    let nat;
    if (manual) { nat = readD20(); if (nat == null) return; }
    else nat = E.rollDie(20);
    const crit = nat === 20;
    const toHitTotal = nat + (atk.tohit || 0);
    let dmgTotal = null;
    if (atk.dmgExpr) {
      if (manual && dmgv !== "") dmgTotal = parseInt(dmgv, 10);
      else { const d = E.rollExpr(atk.dmgExpr, { crit }); dmgTotal = d ? d.total : null; }
    }
    const tgtPc = pcs.find((p) => p.id === tgtId) || null;
    let vs = "", kind = "roll";
    if (tgtPc) { const hh = toHitTotal >= tgtPc.ac || crit; vs = ` vs ${tgtPc.name} AC ${tgtPc.ac} — ${hh ? "HIT" : "miss"}`; kind = hh ? "hit" : "miss"; }
    if (crit) kind = "hit";
    const dmgTxt = dmgTotal != null ? ` · <b>${dmgTotal}</b> ${atk.dmgType}${crit ? " (CRIT)" : ""}` : "";
    const saveTxt = atk.save ? ` · ${atk.save.ability} save DC ${atk.save.dc}` : "";
    push({ kind, html: `${atk.name}: d20+${atk.tohit} = <b>${toHitTotal}</b>${vs}${dmgTxt}${saveTxt}` });
    if (dmgTotal != null && tgtPc) setPending({ dmg: dmgTotal, label: `${dmgTotal} to ${tgtPc.name}`, id: tgtPc.id });
    else setPending(null);
    if (manual) { setD20v(""); setDmgv(""); }
  };

  const activeMon = active && active.side === "mon" && active.mkey ? MON[active.mkey] : null;

  return (
    <div className="ck-dice">
      <div className="ck-dice-row">
        <span className="ck-dice-lbl">Check / attack</span>
        <div className="ck-seg ck-rollmode">
          <button className={!manual ? "on" : ""} onClick={() => setRollMode("app")}>🎲 App</button>
          <button className={manual ? "on" : ""} onClick={() => setRollMode("me")}>✋ I roll</button>
        </div>
        <div className="ck-modbox">
          <button onClick={() => setMod((m) => m - 1)}>−</button>
          <span>mod {mod >= 0 ? "+" + mod : mod}</span>
          <button onClick={() => setMod((m) => m + 1)}>+</button>
        </div>
        {!manual && (
          <div className="ck-seg">
            {["dis", "normal", "adv"].map((mo) => (
              <button key={mo} className={mode === mo ? "on" : ""} onClick={() => setMode(mo)}>
                {mo === "dis" ? "Dis" : mo === "adv" ? "Adv" : "Norm"}
              </button>
            ))}
          </div>
        )}
        <input className="ck-tgt" inputMode="numeric" placeholder="vs AC/DC" value={target}
          onChange={(e) => setTarget(e.target.value.replace(/[^0-9]/g, ""))} />
        {manual ? (
          <div className="ck-manualroll">
            <input className="ck-d20in" inputMode="numeric" placeholder="d20" value={d20v}
              onChange={(e) => setD20v(e.target.value.replace(/[^0-9]/g, ""))}
              onKeyDown={(e) => { if (e.key === "Enter") rollCheck(); }} />
            <button className="ck-rolld20" onClick={rollCheck}>Log →</button>
          </div>
        ) : (
          <button className="ck-rolld20" onClick={rollCheck}>🎲 Roll d20</button>
        )}
      </div>

      <div className="ck-freedice">
        <span className="ck-dice-lbl">{manual ? "or auto-roll" : "quick"}</span>
        {[4, 6, 8, 10, 12, 20, 100].map((s) => <button key={s} onClick={() => rollFree(s)}>d{s}</button>)}
      </div>

      {activeMon && activeMon.attacks.length > 0 && (
        <div className="ck-attacks">
          <span className="ck-dice-lbl">{active.name}’s attacks{manual ? " — type your d20 (above), optional dmg, then tap" : ""}</span>
          <div className="ck-atk-row">
            {pcs.length > 0 && (
              <select className="ck-atk-tgt" value={tgtId} onChange={(e) => setTgtId(e.target.value)}>
                <option value="">target…</option>
                {pcs.map((p) => <option key={p.id} value={p.id}>{p.name} (AC {p.ac})</option>)}
              </select>
            )}
            {manual && (
              <input className="ck-d20in" inputMode="numeric" placeholder="dmg" value={dmgv}
                onChange={(e) => setDmgv(e.target.value.replace(/[^0-9]/g, ""))}
                title="your rolled damage — leave blank to auto-roll" />
            )}
            {activeMon.attacks.map((a, i) => (
              <button key={i} className="ck-atkbtn" onClick={() => rollAttack(a)}>
                {a.name} <small>+{a.tohit}{a.dmgExpr ? " · " + a.dmgExpr : ""}</small>
              </button>
            ))}
          </div>
          {pending && (
            <button className="ck-apply" onClick={() => { onDamage(pending.id, pending.dmg); setPending(null); }}>
              ⤵ Apply {pending.label}
            </button>
          )}
        </div>
      )}

      <div className="ck-log">
        {log.length === 0 && <span className="ck-log-empty">Rolls appear here.</span>}
        {log.map((e) => <div key={e.id} className={"ck-logitem " + e.kind} dangerouslySetInnerHTML={{ __html: e.html }} />)}
      </div>
    </div>
  );
}

/* ============================ BOARD: tokens + drag-an-ability ============================ */
/* Normalize a PC attack / spell / monster action into a uniform "ability" descriptor.
   The resolve popover always lets the DM override the numbers, so heuristics are fine. */
function firstDice(text) {
  const m = String(text || "").match(/(\d+\s*d\s*\d+(?:\s*[+-]\s*\d+)?)/i);
  return m ? m[1].replace(/\s+/g, "") : null;
}
function parseDmgString(s) {
  if (!s) return { expr: null, type: "" };
  const str = String(s).replace(/\s+/g, " ").trim();
  const m = str.match(/(\d+\s*d\s*\d+(?:\s*[+-]\s*\d+)?)/i);
  const expr = m ? m[1].replace(/\s+/g, "") : null;
  const type = (m ? str.slice(m.index + m[0].length) : str).replace(/^[\s,;:·-]+/, "").trim();
  return { expr, type };
}
/* extract an imposed condition (and whether it lands on a hit or a failed save) from ability text */
const COND_WORDS = { prone: "Prone", restrained: "Restrained", grappled: "Grappled", stunned: "Stunned", paralyzed: "Paralyzed", frightened: "Frightened", poisoned: "Poisoned", blinded: "Blinded" };
/* spells whose NAME implies a tracked condition (monster innate/prepared spells carry no effect text) */
const SPELL_COND = { "hold person": "Paralyzed", "hold monster": "Paralyzed", "sleep": "Stunned", "command": "Prone", "color spray": "Blinded", "blindness": "Blinded", "entangle": "Restrained", "web": "Restrained", "ensnaring strike": "Restrained", "fear": "Frightened", "cause fear": "Frightened", "ray of sickness": "Poisoned", "contagion": "Poisoned" };
function parseCond(text) {
  const t = String(text || "");
  for (const w in COND_WORDS) {
    if (new RegExp("\\b" + w + "\\b", "i").test(t)) {
      return { cond: COND_WORDS[w], on: /sav(e|ing)|\bDC\b/i.test(t) ? "fail" : "hit" };
    }
  }
  const low = t.toLowerCase();
  for (const sp in SPELL_COND) { if (low.indexOf(sp) >= 0) return { cond: SPELL_COND[sp], on: "fail" }; }
  return null;
}
/* conditions/actions → advantage/disadvantage on an attack, with a human reason (DM can override).
   Target-side conds grant adv (restrained/stunned/blinded) or depend on melee/ranged (prone);
   attacker-side conds (prone/restrained/frightened/poisoned/blinded) + target Dodge give dis. */
function advInfo(ability, target, source) {
  const reasons = []; let adv = false, dis = false;
  if (!target) return { mode: "normal", reasons };
  const ranged = /ranged|range \d|crossbow|\bbow\b|longbow|shortbow|thrown|\bdart\b|\bsling\b/i.test(ability.note || "");
  const tc = target.conds || [], ta = target.actions || {};
  if (tc.includes("Prone")) { if (ranged) { dis = true; reasons.push("target Prone → disadvantage (ranged)"); } else { adv = true; reasons.push("target Prone → advantage (melee)"); } }
  if (tc.includes("Restrained")) { adv = true; reasons.push("target Restrained → advantage"); }
  if (tc.includes("Stunned")) { adv = true; reasons.push("target Stunned → advantage"); }
  if (tc.includes("Paralyzed")) { adv = true; reasons.push("target Paralyzed → advantage"); }
  if (tc.includes("Blinded")) { adv = true; reasons.push("target Blinded → advantage"); }
  if (ta.dodge) { dis = true; reasons.push("target Dodging → disadvantage"); }
  if (source) {
    const sc = source.conds || [], sa = source.actions || {};
    ["Prone", "Restrained", "Frightened", "Poisoned", "Blinded"].forEach((c) => {
      if (sc.includes(c)) { dis = true; reasons.push(source.name + " " + c + " → disadvantage"); }
    });
    if (sa.dodge) { /* dodging doesn't impair your own attacks */ }
  }
  const mode = (adv && dis) ? "normal" : adv ? "adv" : dis ? "dis" : "normal";
  if (adv && dis) reasons.push("advantage + disadvantage cancel → normal");
  return { mode, reasons };
}
function pcAttackAbility(a) {
  const d = parseDmgString(a.dmg);
  const cc = parseCond(a.note || "");
  return { name: a.name, kind: "attack", tohit: E.toNum(a.bonus), dmgExpr: d.expr, dmgType: d.type, note: a.note || a.range || "", cond: cc ? cc.cond : null, condOn: cc ? cc.on : null, src: a };
}
function pcSpellAbility(sp, s) {
  const roll = s.roll || "", eff = s.effect || "", dice = firstDice(eff);
  let kind = "utility", tohit = null, save = null, dmgExpr = dice, dmgType = "", healExpr = null;
  if (/spell attack/i.test(roll)) { kind = "attack"; tohit = E.toNum(sp.atk); dmgType = "spell"; }
  else if (/hit points|\brestore\b|\bheal/i.test(eff) || /cure|heal/i.test(s.name)) { kind = "heal"; healExpr = dice; dmgExpr = null; }
  else if (/sav(e|ing)/i.test(roll) || /\bDC\b/.test(eff + " " + roll)) {
    kind = "save";
    const ab = (roll + " " + eff).match(/(Str|Dex|Con|Int|Wis|Cha)\w*\s+sav/i);
    save = { dc: sp.dc, ability: ab ? ab[1] : "" };
  }
  const cc = parseCond(eff);
  return { name: s.name, kind, tohit, dmgExpr, dmgType, healExpr, save, note: eff, cond: cc ? cc.cond : null, condOn: cc ? cc.on : null,
    level: s.lvl === "cantrip" ? "cantrip" : "L" + s.lvl, slotLevel: (typeof s.lvl === "number" && s.lvl >= 1) ? s.lvl : null, src: s };
}
function monActionAbility(act) {
  const p = E.parseAttack(act.n, act.t);
  const kind = p.tohit != null ? "attack" : (p.save ? "save" : "utility");
  const cc = parseCond(act.t);
  return { name: act.n, kind, tohit: p.tohit || 0, dmgExpr: p.dmgExpr, dmgType: p.dmgType, save: p.save, note: act.t, cond: cc ? cc.cond : null, condOn: cc ? cc.on : null, src: act };
}
/* monster spellcasting → draggable spell chips. Derive the spell list, save DC and attack
   bonus from the statblock's Spellcasting / Innate Spellcasting trait text (single source of
   truth — no hardcoded per-monster lists). Kind via the same heuristics as PCs; parseCond
   auto-applies condition spells (hold person → Paralyzed, etc.). DM overrides in the popover. */
const SP_HEAL = /\b(cure wounds|healing word|mass cure|heal\b|prayer of healing)/i;
const SP_ATK = /\b(inflict wounds|guiding bolt|fire bolt|firebolt|ray of frost|chill touch|shocking grasp|eldritch blast|witch bolt|scorching ray|thorn whip|produce flame|spiritual weapon|acid splash|poison spray|frostbite)\b/i;
const SP_UTIL = /\b(light|thaumaturgy|dancing lights|minor illusion|major image|silent image|mage armor|shield of faith|bless|aid|invisibility|disguise self|silence|darkness|fog cloud|detect magic|mending|message|prestidigitation|spare the dying|guidance|resistance|pass without trace|misty step)\b/i;
const titleCase = (s) => String(s).replace(/\b\w/g, (m) => m.toUpperCase());
function monSpellAbilities(sb) {
  const out = [];
  (sb.traits || []).forEach((tr) => {
    if (!/spellcasting/i.test(tr.n || "")) return;
    const raw = String(tr.t || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
    const dc = (raw.match(/save\s*DC\s*(\d+)/i) || [])[1];
    const atk = (raw.match(/([+\-−–]\s*\d+)\s*to hit/i) || [])[1];
    const cab = (raw.match(/\b(Str|Dex|Con|Int|Wis|Cha)\b/i) || [])[1] || "";
    const re = /(Cantrips?|At will|\d+\s*\/\s*day(?:\s+each)?|\d+(?:st|nd|rd|th))\s*(?:\([^)]*\))?\s*:\s*([^;.]+)/gi;
    let m;
    while ((m = re.exec(raw))) {
      const lvl = /cantrip/i.test(m[1]) ? "cantrip" : m[1].toLowerCase().replace(/\s+/g, " ").trim();
      m[2].split(",").forEach((nm) => {
        const name = nm.trim().replace(/[.;]+$/, "");
        if (!name) return;
        const low = name.toLowerCase();
        const cc = parseCond(name);
        let kind = "utility", tohit = null, save = null, dmgType = "", healExpr = null;
        if (SP_HEAL.test(low)) kind = "heal";
        else if (SP_ATK.test(low)) { kind = "attack"; tohit = E.toNum(atk); dmgType = "spell"; }
        else if (SP_UTIL.test(low) && !cc) kind = "utility";
        else if (cc || dc) { kind = "save"; save = { dc: dc ? +dc : null, ability: cab }; }
        out.push({ name: titleCase(name), kind, tohit, dmgExpr: null, dmgType, healExpr, save, note: name, level: lvl, cond: cc ? cc.cond : null, condOn: cc ? cc.on : "fail", src: null });
      });
    }
  });
  return out;
}
function abilitiesFor(c) {
  if (c.side === "pc") {
    const pc = PARTY_BY_SLUG[c.slug]; if (!pc) return [];
    const out = (pc.attacks || []).map(pcAttackAbility);
    if (pc.spell) [].concat(pc.spell.cantrips || []).concat(pc.spell.known || pc.spell.prepared || []).forEach((s) => out.push(pcSpellAbility(pc.spell, s)));
    return out;
  }
  const sb = SB[c.mkey]; if (!sb) return [];
  const acts = (sb.actions || []).map(monActionAbility).filter((a) => a.kind === "attack" || a.kind === "save");
  return acts.concat(monSpellAbilities(sb));
}
function tokLabel(c) {
  if (c.side === "pc") return (c.name || "?").trim().charAt(0).toUpperCase();
  const m = (c.name || "").match(/^(.*?)\s*(\d+)\s*$/);
  return m ? (m[1].charAt(0).toUpperCase() + m[2]) : (c.name || "?").slice(0, 3);
}
/* readable name shown ABOVE the token (PCs: first name; monsters: the numbered name e.g. "Wolf 3") */
const tokName = (c) => (c.side === "pc" ? (c.name || "").trim().split(/\s+/)[0] : (c.name || "").trim()) || "?";

/* level/slot label for chips + tooltip ("L1" / "cantrip" / "1st" / "At will" / "3/day each") */
function abilLevelLabel(ability) {
  const lv = ability.level;
  if (!lv) return "";
  const s = String(lv);
  return s.charAt(0).toUpperCase() + s.slice(1);
}
/* Click (not drag) on an ability chip → a read-only detail tooltip. PC spells/attacks and monster
   actions carry full text (ability.src = the raw spell/attack/action); monster spells only have a
   name in the data, so we show the derived fields + a note. (Richer monster-spell text = add a
   field to the data file, not hardcode here.) */
function AbilityTip({ ability, posStyle, onClose }) {
  const s = ability.src || null;
  const rows = [];
  const lvl = abilLevelLabel(ability);
  if (lvl) rows.push(["Level", lvl]);
  if (s && s.castTime) rows.push(["Cast", s.castTime]);
  else if (s && s.use) rows.push(["Action", s.use]);
  if (s && s.range) rows.push(["Range", s.range]);
  if (ability.kind === "attack") rows.push(["To hit", "+" + (ability.tohit || 0)]);
  if (ability.dmgExpr) rows.push(["Damage", ability.dmgExpr + (ability.dmgType ? " " + ability.dmgType : "")]);
  if (ability.save && ability.save.dc != null) rows.push(["Save", "DC " + ability.save.dc + (ability.save.ability ? " " + ability.save.ability : "")]);
  if (ability.healExpr) rows.push(["Heal", ability.healExpr]);
  if (s && s.concentration) rows.push(["Concentration", "yes"]);
  if (s && s.duration) rows.push(["Duration", s.duration]);
  if (ability.cond) rows.push(["Condition", ability.cond + " (on " + (ability.condOn || "hit") + ")"]);
  let textHtml = null, textPlain = null;
  if (s && s.effect) textPlain = s.effect;          // PC spell effect
  else if (s && s.note) textPlain = s.note;          // PC attack note
  else if (s && s.t) textHtml = s.t;                 // monster action (HTML)
  else textPlain = "No description in the stat block — narrate from the spell's name + level.";
  if (s && s.when) textPlain = (textPlain ? textPlain + "  " : "") + "▸ " + s.when;
  return (
    <div className="ck-tip" style={posStyle}>
      <div className="ck-tip-head"><b>{ability.name}</b><button className="ck-tip-x" onClick={onClose}>✕</button></div>
      {rows.length > 0 && <div className="ck-tip-rows">{rows.map((r, i) => (
        <div key={i} className="ck-tip-row"><span className="ck-tip-k">{r[0]}</span><span className="ck-tip-v">{r[1]}</span></div>
      ))}</div>}
      {textHtml ? <div className="ck-tip-text" dangerouslySetInnerHTML={{ __html: textHtml }} />
        : <div className="ck-tip-text">{textPlain}</div>}
    </div>
  );
}

/* Popover shown when an ability chip is dropped on a target. Honors the roll mode
   (app = auto-roll via TWGE; me = the DM types the numbers). Applies via damage/heal + logs. */
function ResolvePopover({ ability, target, source, rollMode, onDamage, onHeal, onPatch, onLog, onClose, posStyle }) {
  const manual = rollMode === "me";
  const adv = advInfo(ability, target, source);
  const [d20v, setD20v] = useState("");
  const [dmgv, setDmgv] = useState("");
  const [res, setRes] = useState(null);
  const [mode, setMode] = useState(adv.mode);   // pre-picked from conditions; DM can override
  const roll = () => {
    if (ability.kind === "heal") { const r = E.rollExpr(ability.healExpr || "0"); setRes({ heal: r ? r.total : 0 }); return; }
    const r = E.d20(ability.tohit || 0, mode), nat = r.die, crit = r.nat20, total = r.total;
    const hit = ability.kind === "save" ? null : (total >= target.ac || crit);
    let dmg = null; if (ability.dmgExpr) { const d = E.rollExpr(ability.dmgExpr, { crit }); dmg = d ? d.total : null; }
    setRes({ nat, total, hit, crit, dmg, dice: r.dice });
  };
  useEffect(() => { if (!manual) roll(); }, [mode]);
  const applyCond = () => { if (ability.cond && onPatch) onPatch(target.id, (cc) => ({ conds: cc.conds.includes(ability.cond) ? cc.conds : [...cc.conds, ability.cond] })); };
  const condNote = ability.cond ? ` · ${condIcon(ability.cond)} ${ability.cond}` : "";
  const saveHint = (() => {
    if (!ability.save) return "";
    const ab = (ability.save.ability || "").slice(0, 3).toLowerCase(), tc = target.conds || [];
    if (tc.includes("Paralyzed") && (ab === "str" || ab === "dex")) return "target Paralyzed → auto-fails Str/Dex saves";
    if (tc.includes("Stunned") && (ab === "str" || ab === "dex")) return "target Stunned → auto-fails Str/Dex saves";
    if (tc.includes("Restrained") && ab === "dex") return "target Restrained → disadvantage on Dex saves";
    return "";
  })();
  const dmgVal = () => manual ? (parseInt(dmgv, 10) || 0) : (res ? res.dmg || 0 : 0);
  const healVal = () => manual ? (parseInt(dmgv, 10) || 0) : (res ? res.heal || 0 : 0);
  const crit = () => manual ? (parseInt(d20v, 10) === 20) : (res ? res.crit : false);
  const total = () => manual ? ((parseInt(d20v, 10) || 0) + (ability.tohit || 0)) : (res ? res.total : 0);
  const hit = () => manual ? (total() >= target.ac || crit()) : (res ? res.hit : false);

  /* resolving an ability spends the source's economy: mark its Action used, and decrement the
     matching spell slot / innate use for a leveled spell (cantrips/at-will/weapons cost no slot).
     A slot is spent whether the attack hits or the save succeeds. DM can re-toggle in the panel. */
  const spend = () => {
    if (!source || !onPatch) return;
    const sp = spendOf(ability);
    onPatch(source.id, (cc) => {
      const patch = { econ: { action: true, bonus: !!(cc.econ && cc.econ.bonus), reaction: !!(cc.econ && cc.econ.reaction) } };
      if (sp && sp.kind === "slot") { const cur = (cc.slots && cc.slots[sp.lvl]) || 0; patch.slots = { ...(cc.slots || {}), [sp.lvl]: Math.max(0, cur - 1) }; }
      else if (sp && sp.kind === "innate") { const cur = (cc.innate && cc.innate[sp.key]) || 0; patch.innate = { ...(cc.innate || {}), [sp.key]: Math.max(0, cur - 1) }; }
      return patch;
    });
  };

  const applyAttack = () => {
    const isHit = hit(), dmg = dmgVal();
    if (isHit && dmg) onDamage(target.id, dmg);
    if (isHit) applyCond();
    onLog({ kind: isHit ? "hit" : "miss", html: `${ability.name} → <b>${target.name}</b> (AC ${target.ac}): d20+${ability.tohit || 0} = <b>${total()}</b> — ${isHit ? "HIT" : "miss"}${isHit && dmg ? ` · <b>${dmg}</b> ${ability.dmgType || ""}${crit() ? " (CRIT)" : ""}` : ""}${isHit ? condNote : ""}` });
    spend();
    onClose();
  };
  const applySave = (out) => {
    const dmg = dmgVal(), applied = out === "fail" ? dmg : out === "half" ? Math.floor(dmg / 2) : 0;
    if (applied) onDamage(target.id, applied);
    if (out === "fail") applyCond();
    onLog({ kind: out === "fail" ? "hit" : "roll", html: `${ability.name} → <b>${target.name}</b>: DC ${ability.save ? ability.save.dc : "?"} ${ability.save ? ability.save.ability : ""} save — ${out === "fail" ? "FAILED" : out === "half" ? "saved ½" : "saved"}${applied ? ` · <b>${applied}</b> ${ability.dmgType || ""}` : ""}${out === "fail" ? condNote : ""}` });
    spend();
    onClose();
  };
  const applyHeal = () => { const amt = healVal(); if (amt) onHeal(target.id, amt); onLog({ kind: "roll", html: `${ability.name} → <b>${target.name}</b>: healed <b>${amt}</b>` }); spend(); onClose(); };
  const applyUtil = () => { onLog({ kind: "roll", html: `${ability.name} → <b>${target.name}</b>` }); spend(); onClose(); };

  const head = (
    <div className="ck-pop-head">
      <b>{ability.name}</b><span className="ck-pop-arrow">{"→ " + target.name}</span>
      <button className="ck-pop-x" onClick={onClose}>✕</button>
    </div>
  );
  let body;
  if (ability.kind === "attack") {
    body = (
      <div className="ck-pop-body">
        <div className="ck-pop-adv">
          <div className="ck-seg ck-pop-mode">
            {["dis", "normal", "adv"].map((mo) => (
              <button key={mo} className={mode === mo ? "on" : ""} onClick={() => setMode(mo)}>{mo === "dis" ? "Dis" : mo === "adv" ? "Adv" : "Norm"}</button>
            ))}
          </div>
          {adv.reasons.length > 0 && <span className="ck-pop-why">{adv.reasons.join(" · ")}</span>}
        </div>
        {manual ? (
          <div className="ck-pop-row">
            <label>d20</label>
            <input className="ck-d20in sm" inputMode="numeric" autoFocus value={d20v} onChange={(e) => setD20v(e.target.value.replace(/[^0-9]/g, ""))} />
            <span className="ck-pop-eq">{"+" + (ability.tohit || 0) + " = " + total()}</span>
            <span className={hit() ? "ck-pop-hit" : "ck-pop-miss"}>{"vs AC " + target.ac + " · " + (hit() ? "HIT" : "miss")}</span>
          </div>
        ) : (
          <div className="ck-pop-row">
            <span className={res && res.hit ? "ck-pop-hit" : "ck-pop-miss"}>{"d20 " + (res ? res.nat : "?") + (res && res.dice && res.dice.length > 1 ? " [" + res.dice.join("/") + "]" : "") + "+" + (ability.tohit || 0) + " = " + total() + " vs AC " + target.ac + " · " + (res && res.hit ? "HIT" : "miss") + (res && res.crit ? " CRIT" : "")}</span>
            <button className="ck-pop-btn ghost" onClick={roll}>🎲</button>
          </div>
        )}
        <div className="ck-pop-row">
          <label>dmg</label>
          {manual
            ? <input className="ck-d20in" inputMode="numeric" placeholder={ability.dmgExpr || "#"} value={dmgv} onChange={(e) => setDmgv(e.target.value.replace(/[^0-9]/g, ""))} />
            : <span className="ck-pop-dmg">{(res && res.dmg != null ? res.dmg : "—") + " " + (ability.dmgType || "") + (ability.dmgExpr ? " (" + ability.dmgExpr + ")" : "")}</span>}
        </div>
        {ability.cond && <div className="ck-pop-why cond">{condIcon(ability.cond) + " applies " + ability.cond + " on hit"}</div>}
        <button className="ck-pop-btn apply" onClick={applyAttack}>{hit() ? ("⚔ Apply " + dmgVal() + " dmg") : "Log miss"}</button>
      </div>
    );
  } else if (ability.kind === "save") {
    body = (
      <div className="ck-pop-body">
        <div className="ck-pop-save">{"DC " + (ability.save ? ability.save.dc : "?") + " " + (ability.save ? ability.save.ability : "") + " save — player rolls"}</div>
        {saveHint && <div className="ck-pop-why">{saveHint}</div>}
        {ability.cond && <div className="ck-pop-why cond">{condIcon(ability.cond) + " applies " + ability.cond + " on failed save"}</div>}
        <div className="ck-pop-row">
          <label>dmg</label>
          {manual
            ? <input className="ck-d20in" inputMode="numeric" placeholder={ability.dmgExpr || "#"} value={dmgv} onChange={(e) => setDmgv(e.target.value.replace(/[^0-9]/g, ""))} />
            : <span className="ck-pop-dmg">{(res && res.dmg != null ? res.dmg : "—") + " " + (ability.dmgType || "")}</span>}
          {!manual && ability.dmgExpr && <button className="ck-pop-btn ghost" onClick={roll}>🎲</button>}
        </div>
        <div className="ck-pop-saverow">
          <button className="ck-pop-btn fail" onClick={() => applySave("fail")}>Failed — full</button>
          <button className="ck-pop-btn" onClick={() => applySave("half")}>Saved — ½</button>
          <button className="ck-pop-btn ghost" onClick={() => applySave("none")}>None</button>
        </div>
      </div>
    );
  } else if (ability.kind === "heal") {
    body = (
      <div className="ck-pop-body">
        <div className="ck-pop-row">
          <label>heal</label>
          {manual
            ? <input className="ck-d20in" inputMode="numeric" autoFocus placeholder={ability.healExpr || "#"} value={dmgv} onChange={(e) => setDmgv(e.target.value.replace(/[^0-9]/g, ""))} />
            : <span className="ck-pop-dmg">{(res ? res.heal : "—") + (ability.healExpr ? " (" + ability.healExpr + ")" : "")}</span>}
          {!manual && <button className="ck-pop-btn ghost" onClick={roll}>🎲</button>}
        </div>
        <button className="ck-pop-btn apply heal" onClick={applyHeal}>{"✚ Apply " + healVal() + " heal"}</button>
      </div>
    );
  } else {
    body = (
      <div className="ck-pop-body">
        <div className="ck-pop-note">{ability.note || "No roll — narrate it."}</div>
        <button className="ck-pop-btn apply" onClick={applyUtil}>{"Log on " + target.name}</button>
      </div>
    );
  }
  return <div className="ck-pop" style={posStyle}>{head}{body}</div>;
}

function BoardView({ sorted, active, st, up, onDamage, onHeal, onPatch, onRemove, onLog, version, onSetTurn }) {
  const boardRef = useRef(null);
  const worldRef = useRef(null);   // the scaled+translated "world" layer (grid + tokens + rings + ruler)
  const dragRef = useRef(null);
  const chipRef = useRef(null);
  const panRef = useRef(null);
  const [drag, setDrag] = useState(null);
  const [chip, setChip] = useState(null);
  const [abilTip, setAbilTip] = useState(null);   // {ability,x,y} — chip clicked (not dragged) → detail tooltip
  const [resolve, setResolve] = useState(null);
  const [rulerMode, setRulerMode] = useState(false);
  const [ruler, setRuler] = useState(null);   // {x1,y1,x2,y2,ft} in *untransformed world px* (scale with zoom)
  const [panning, setPanning] = useState(false);
  const [vp, setVp] = useState({ zoom: 1, x: 0, y: 0 });   // viewport: scale + pan (px). Ephemeral — not persisted.
  const rulerRef = useRef(null);

  /* world point (untransformed px) under a client coordinate, honouring the current zoom/pan */
  const worldPt = (cx, cy) => {
    const rect = worldRef.current.getBoundingClientRect();   // post-transform box → already includes zoom+pan
    return { x: (cx - rect.left) / vp.zoom, y: (cy - rect.top) / vp.zoom };
  };

  /* scroll-wheel zoom toward the cursor (native non-passive so preventDefault stops page scroll) */
  const onWheel = useCallback((e) => {
    e.preventDefault();
    const el = boardRef.current; if (!el) return;
    const rect = el.getBoundingClientRect();
    const mx = e.clientX - rect.left, my = e.clientY - rect.top;   // cursor in surface-local px
    const factor = e.deltaY < 0 ? 1.12 : 1 / 1.12;
    setVp((v) => {
      const nz = clamp(+(v.zoom * factor).toFixed(3), ZMIN, ZMAX);
      const wx = (mx - v.x) / v.zoom, wy = (my - v.y) / v.zoom;   // world point under cursor (keep it fixed)
      return { zoom: nz, x: mx - wx * nz, y: my - wy * nz };
    });
  }, [vp.zoom]);
  useEffect(() => {
    const el = boardRef.current; if (!el) return;
    el.addEventListener("wheel", onWheel, { passive: false });
    return () => el.removeEventListener("wheel", onWheel);
  }, [onWheel]);
  const zoomBy = (factor) => setVp((v) => {
    const el = boardRef.current, mx = el ? el.clientWidth / 2 : 0, my = el ? el.clientHeight / 2 : 0;
    const nz = clamp(+(v.zoom * factor).toFixed(3), ZMIN, ZMAX);
    const wx = (mx - v.x) / v.zoom, wy = (my - v.y) / v.zoom;
    return { zoom: nz, x: mx - wx * nz, y: my - wy * nz };
  });
  const resetView = () => setVp({ zoom: 1, x: 0, y: 0 });

  /* surface pointer: distance ruler (ruler mode) OR drag-to-pan (otherwise) on empty board.
     Tokens/controls handle their own pointers, so skip them here. */
  const onSurface = (e) => e.target.closest && e.target.closest("[data-tokenid], button, input, .ck-pop, .ck-detail");
  const surfDown = (e) => {
    if (e.button || onSurface(e)) return;
    setAbilTip(null);                              // tapping the board dismisses an open chip tooltip
    if (rulerMode) {
      const p = worldPt(e.clientX, e.clientY);
      rulerRef.current = { x1: p.x, y1: p.y };
      setRuler({ x1: p.x, y1: p.y, x2: p.x, y2: p.y, ft: 0 });
    } else {
      panRef.current = { sx: e.clientX, sy: e.clientY, px: vp.x, py: vp.y };
      setPanning(true);
    }
    try { e.currentTarget.setPointerCapture(e.pointerId); } catch (z) {}
  };
  const surfMove = (e) => {
    if (rulerRef.current) {
      const d = rulerRef.current, p = worldPt(e.clientX, e.clientY);
      setRuler({ x1: d.x1, y1: d.y1, x2: p.x, y2: p.y, ft: ftBetween(d.x1, d.y1, p.x, p.y) });
    } else if (panRef.current) {
      const d = panRef.current;
      setVp((v) => ({ ...v, x: d.px + (e.clientX - d.sx), y: d.py + (e.clientY - d.sy) }));
    }
  };
  const surfUp = (e) => { rulerRef.current = null; panRef.current = null; setPanning(false); try { e.currentTarget.releasePointerCapture(e.pointerId); } catch (z) {} };

  const startToken = (e, c) => {
    if (e.button) return;
    setAbilTip(null);
    const rect = worldRef.current.getBoundingClientRect();   // post-transform → fractions stay correct under zoom/pan
    dragRef.current = { id: c.id, sx: e.clientX, sy: e.clientY, offX: e.clientX - (rect.left + c.x * rect.width), offY: e.clientY - (rect.top + c.y * rect.height), moved: false, lx: c.x, ly: c.y };
    try { e.currentTarget.setPointerCapture(e.pointerId); } catch (x) {}
  };
  const moveToken = (e) => {
    const d = dragRef.current; if (!d) return;
    if (!d.moved && Math.hypot(e.clientX - d.sx, e.clientY - d.sy) < 5) return;
    d.moved = true;
    const rect = worldRef.current.getBoundingClientRect();
    d.lx = clamp((e.clientX - d.offX - rect.left) / rect.width, 0.03, 0.97);
    d.ly = clamp((e.clientY - d.offY - rect.top) / rect.height, 0.05, 0.95);
    setDrag({ id: d.id, x: d.lx, y: d.ly });
  };
  const endToken = (e, c) => {
    const d = dragRef.current; dragRef.current = null;
    try { e.currentTarget.releasePointerCapture(e.pointerId); } catch (x) {}
    if (d && d.moved) onPatch(c.id, { x: d.lx, y: d.ly });
    else { setAbilTip(null); up({ selId: c.id }); if (onSetTurn && st.round > 0) onSetTurn(c.id); }  // tap = select + (mid-fight) make it this combatant's turn
    setDrag(null);
  };

  const tokenAt = (x, y) => { const el = document.elementFromPoint(x, y); const t = el && el.closest ? el.closest("[data-tokenid]") : null; return t ? t.getAttribute("data-tokenid") : null; };
  const startChip = (e, ability) => {
    if (e.button) return;
    chipRef.current = { ability, sx: e.clientX, sy: e.clientY, moved: false };  // track movement so we can tell a click (tooltip) from a drag (apply)
    try { e.currentTarget.setPointerCapture(e.pointerId); } catch (x) {}
    e.preventDefault();
  };
  const moveChip = (e) => {
    const cr = chipRef.current; if (!cr) return;
    if (!cr.moved && Math.hypot(e.clientX - cr.sx, e.clientY - cr.sy) < 5) return;   // same <5px threshold as token drag
    cr.moved = true;
    setChip({ ability: cr.ability, x: e.clientX, y: e.clientY, overId: tokenAt(e.clientX, e.clientY) });
  };
  const endChip = (e) => {
    const cr = chipRef.current; chipRef.current = null;
    try { e.currentTarget.releasePointerCapture(e.pointerId); } catch (x) {}
    if (!cr) return;
    if (!cr.moved) {                                   // click (no drag) → show the ability detail tooltip
      setChip(null);
      if (cr.ability.kind === "condition") return;     // conditions have no detail to show
      setAbilTip({ ability: cr.ability, x: e.clientX, y: e.clientY });
      return;
    }
    const targetId = tokenAt(e.clientX, e.clientY);
    setChip(null);
    if (!targetId) return;
    const ability = cr.ability;
    if (ability.kind === "condition") {
      onPatch(targetId, (cc) => ({ conds: cc.conds.includes(ability.cond) ? cc.conds : [...cc.conds, ability.cond] }));
      const tg = sorted.find((c) => c.id === targetId);
      onLog({ kind: "roll", html: `${condIcon(ability.cond)} ${ability.cond} → <b>${tg ? tg.name : "?"}</b>` });
    } else setResolve({ ability, targetId, sourceId: st.selId });
  };

  const sel = sorted.find((c) => c.id === st.selId) || null;
  const resTarget = resolve ? sorted.find((c) => c.id === resolve.targetId) : null;
  let posStyle = null;
  if (resTarget && worldRef.current) {
    const rect = worldRef.current.getBoundingClientRect();   // post-transform → token's real screen box
    const vw = window.innerWidth, vh = window.innerHeight;
    posStyle = { left: clamp(rect.left + resTarget.x * rect.width, 140, vw - 140) + "px", top: clamp(rect.top + resTarget.y * rect.height + 26, 70, vh - 200) + "px" };
  }
  let tipStyle = null;
  if (abilTip) { const vw = window.innerWidth, vh = window.innerHeight; tipStyle = { left: clamp(abilTip.x, 150, vw - 150) + "px", top: clamp(abilTip.y + 14, 60, vh - 220) + "px" }; }
  const worldStyle = { transform: `translate(${vp.x}px,${vp.y}px) scale(${vp.zoom})`, transformOrigin: "0 0" };

  return (
    <div className={"ck-board" + (sel ? " has-detail" : "")}>
      <div className={"ck-surface" + (panning ? " panning" : "") + (rulerMode ? " ruling" : "")} ref={boardRef}
        onPointerDown={surfDown} onPointerMove={surfMove} onPointerUp={surfUp}>
        <button className={"ck-ruler-btn" + (rulerMode ? " on" : "")} title="distance ruler (drag on the board)"
          onClick={() => { setRulerMode((m) => !m); setRuler(null); }}>📏</button>
        <div className="ck-zoom">
          <button className="ck-zoom-out" title="zoom out" onClick={() => zoomBy(1 / 1.2)}>−</button>
          <button className="ck-zoom-reset" title="reset view" onClick={resetView}>{Math.round(vp.zoom * 100) + "%"}</button>
          <button className="ck-zoom-in" title="zoom in" onClick={() => zoomBy(1.2)}>+</button>
        </div>
        {sorted.length === 0 && <p className="ck-board-empty">Add fighters from the roster, then drag them into position.</p>}
        <div className="ck-world" ref={worldRef} style={worldStyle}>
          {ruler && <svg className="ck-ruler-svg"><line x1={ruler.x1} y1={ruler.y1} x2={ruler.x2} y2={ruler.y2} /></svg>}
          {sorted.map((c) => {
            const dragging = drag && drag.id === c.id;
            const x = dragging ? drag.x : c.x, y = dragging ? drag.y : c.y;
            const down = c.hp <= 0;
            const pct = clamp((c.hp / c.maxhp) * 100, 0, 100);
            const band = down || pct <= 25 ? "crit" : pct <= 50 ? "low" : "ok";
            const bloodied = !down && pct <= 50;
            const pc = c.side === "pc" ? PARTY_BY_SLUG[c.slug] : null;
            const sil = tokSil(c);
            const acts = c.actions ? Object.keys(c.actions).filter((k) => c.actions[k]) : [];
            const ringSel = !down && ((c.id === st.selId) || (active && c.id === active.id));
            const reachD = (speedOf(c) / 5) * CELL_PX * 2;
            const cls = "ck-tok " + c.side + (c.id === st.selId ? " sel" : "") + (active && c.id === active.id ? " active" : "") + (chip && chip.overId === c.id ? " over" : "") + (bloodied ? " bloodied" : "") + (down ? " down" : "") + (dragging ? " dragging" : "");
            return (
              <div key={c.id} data-tokenid={c.id} className={cls} title={c.name} style={{ left: x * 100 + "%", top: y * 100 + "%" }}
                onPointerDown={(e) => startToken(e, c)} onPointerMove={moveToken} onPointerUp={(e) => endToken(e, c)}>
                <span className="ck-tok-name">{tokName(c)}</span>
                {ringSel && c.actions && c.actions.dash && <div className="ck-ring dash" style={{ width: reachD * 2, height: reachD * 2 }} />}
                {ringSel && <div className="ck-ring reach" style={{ width: reachD, height: reachD }} />}
                <span className="ck-tok-label">
                  {sil && <span className="ck-tok-sil" dangerouslySetInnerHTML={{ __html: sil }} />}
                  {pc && pc.portrait
                    ? <img className="ck-tok-img" src={pc.portrait} alt="" draggable={false} onError={(e) => { e.target.style.display = "none"; }} />
                    : <span className="ck-tok-txt">{tokLabel(c)}</span>}
                </span>
                <div className="ck-tok-hp"><i className={band} style={{ width: pct + "%" }} /></div>
                <span className="ck-tok-hpn">{c.hp + "/" + c.maxhp}</span>
                {c.conds.length > 0 && <div className="ck-tok-conds">{c.conds.slice(0, 4).map((cd) => <span key={cd} className="ck-tok-cond" title={cd}>{condIcon(cd)}</span>)}</div>}
                {acts.length > 0 && <div className="ck-tok-acts">{acts.map((k) => <span key={k} className="ck-tok-act" title={k}>{ACT_ICON[k]}</span>)}</div>}
                {active && c.id === active.id && !down && <div className="ck-tok-econ">{ECON.map((a) => <span key={a.k} className={"ck-tok-econd" + ((c.econ && c.econ[a.k]) ? " used" : "")} title={a.title + (c.econ && c.econ[a.k] ? " — used" : " — available")}>{a.label}</span>)}</div>}
                {down && <span className="ck-tok-down">{c.deaths && c.deaths.f >= 3 ? "💀" : "🩸"}</span>}
              </div>
            );
          })}
        </div>
        {ruler && <div className="ck-ruler-lbl" style={{ left: vp.x + ruler.x2 * vp.zoom + 8, top: vp.y + ruler.y2 * vp.zoom + 8 }}>{ruler.ft} ft</div>}
        {chip && <div className="ck-chip-ghost" style={{ left: chip.x + "px", top: chip.y + "px" }}>{chip.ability.name}</div>}
        {resTarget && (
          <ResolvePopover key={resTarget.id + resolve.ability.name} ability={resolve.ability} target={resTarget}
            source={sorted.find((c) => c.id === resolve.sourceId) || null} rollMode={st.roll}
            onDamage={onDamage} onHeal={onHeal} onPatch={onPatch} onLog={onLog} onClose={() => setResolve(null)} posStyle={posStyle} />
        )}
        {abilTip && <AbilityTip ability={abilTip.ability} posStyle={tipStyle} onClose={() => setAbilTip(null)} />}
      </div>
      <BoardDetail sel={sel} onClose={() => up({ selId: null })} onPatch={onPatch} onDamage={onDamage} onHeal={onHeal} onRemove={onRemove}
        startChip={startChip} moveChip={moveChip} endChip={endChip} />
    </div>
  );
}

function BoardDetail({ sel, onClose, onPatch, onDamage, onHeal, onRemove, startChip, moveChip, endChip }) {
  const [amt, setAmt] = useState("");
  if (!sel) return null;   // overlay panel: hidden until a token is selected, so the map stays reachable
  const pc = sel.side === "pc" ? PARTY_BY_SLUG[sel.slug] : null;
  const abilities = abilitiesFor(sel);
  const apply = (sign) => { const n = parseInt(amt, 10); if (isNaN(n) || !n) return; sign > 0 ? onHeal(sel.id, n) : onDamage(sel.id, n); setAmt(""); };
  /* action economy + spell slots (DM-overridable). `seed` = full counts from the data; sel.slots = remaining. */
  const econ = sel.econ || emptyEcon();
  const seed = slotsFor(sel);
  const slotLevels = Object.keys(seed.slots).map(Number).sort((a, b) => a - b);
  const innateNames = Object.keys(seed.innate);
  const caster = slotLevels.length > 0 || innateNames.length > 0;
  const toggleE = (k) => onPatch(sel.id, (cc) => ({ econ: { action: false, bonus: false, reaction: false, ...(cc.econ || {}), [k]: !(cc.econ && cc.econ[k]) } }));
  const setSlot = (lv, rem) => onPatch(sel.id, (cc) => ({ slots: { ...(cc.slots || {}), [lv]: rem } }));
  const setInn = (nm, rem) => onPatch(sel.id, (cc) => ({ innate: { ...(cc.innate || {}), [nm]: rem } }));
  const doRest = () => onPatch(sel.id, (cc) => { const sd = slotsFor(cc); return { slots: sd.slots, innate: sd.innate, econ: emptyEcon() }; });
  const pips = (rem, max, onSet) => (
    <span className="ck-slotpips">{Array.from({ length: max }, (_, i) => (
      <button key={i} className={"ck-pip" + (i < rem ? " on" : "")} title={i < rem ? "spend" : "restore"} onClick={() => onSet(i < rem ? i : i + 1)} />
    ))}</span>
  );
  const chip = (a, i) => (
    <button key={i} className={"ck-chip ck-chip-" + a.kind} title="drag onto a target"
      onPointerDown={(e) => startChip(e, a)} onPointerMove={moveChip} onPointerUp={endChip}>
      <span className="ck-chip-name">{a.name}</span>
      <small>{(a.level ? a.level + " · " : "") + (a.kind === "attack" ? ("+" + (a.tohit || 0) + (a.dmgExpr ? " · " + a.dmgExpr : "")) : a.kind === "save" ? ("DC " + (a.save && a.save.dc != null ? a.save.dc : "?") + (a.save && a.save.ability ? " " + a.save.ability : "")) : a.kind === "heal" ? (a.healExpr || "heal") : "effect")}</small>
    </button>
  );
  return (
    <div className="ck-detail open">
      <div className="ck-detail-head">
        <b className="ck-detail-name">{sel.name}</b>
        <span className="ck-detail-ac">{"🛡" + sel.ac}</span>
        <button className="ck-detail-rm" title="remove from fight" onClick={() => onRemove(sel.id)}>🗑</button>
        <button className="ck-detail-close" title="close — back to the map" onClick={onClose}>✕</button>
      </div>
      <div className="ck-detail-hp">
        <span className="ck-detail-hpn">{sel.hp + "/" + sel.maxhp + " HP"}</span>
        <input className="ck-amt" inputMode="numeric" placeholder="#" value={amt}
          onChange={(e) => setAmt(e.target.value.replace(/[^0-9]/g, ""))} onKeyDown={(e) => { if (e.key === "Enter") apply(-1); }} />
        <button className="ck-dmg" onClick={() => apply(-1)} title="damage">−</button>
        <button className="ck-heal" onClick={() => apply(1)} title="heal">+</button>
      </div>
      <div className="ck-detail-sec">
        <h6>Move {"·"} <span className="ck-move-ft">{speedOf(sel)} ft{sel.actions && sel.actions.dash ? " · Dash " + speedOf(sel) * 2 + " ft" : ""}</span></h6>
        <div className="ck-actbar">
          {ACTIONS.map((a) => (
            <button key={a.k} className={"ck-actbtn" + (sel.actions && sel.actions[a.k] ? " on" : "")}
              onClick={() => onPatch(sel.id, (cc) => ({ actions: { ...(cc.actions || {}), [a.k]: !(cc.actions && cc.actions[a.k]) } }))}>
              {a.icon} {a.label}
            </button>
          ))}
        </div>
      </div>
      <div className="ck-detail-sec ck-econ-sec">
        <h6>Action economy <button className="ck-rest" title="restore action economy + all spell slots (short/long rest)" onClick={doRest}>↺ rest</button></h6>
        <div className="ck-econ">
          {ECON.map((a) => (
            <button key={a.k} className={"ck-econbtn" + (econ[a.k] ? " used" : "")}
              title={a.title + (econ[a.k] ? " — used (click to restore)" : " — available (click to mark used)")} onClick={() => toggleE(a.k)}>{a.label}</button>
          ))}
        </div>
        {caster && (
          <div className="ck-slots">
            {slotLevels.map((lv) => (
              <div key={"L" + lv} className="ck-slotrow">
                <span className="ck-slotlbl">L{lv}</span>
                {pips((sel.slots && sel.slots[lv]) || 0, seed.slots[lv], (r) => setSlot(lv, r))}
                <span className="ck-slotnum">{((sel.slots && sel.slots[lv]) || 0) + "/" + seed.slots[lv]}</span>
              </div>
            ))}
            {innateNames.map((nm) => (
              <div key={nm} className="ck-slotrow">
                <span className="ck-slotlbl">{titleCase(nm)}</span>
                {pips((sel.innate && sel.innate[nm]) || 0, seed.innate[nm], (r) => setInn(nm, r))}
                <span className="ck-slotnum">{((sel.innate && sel.innate[nm]) || 0) + "/" + seed.innate[nm]}</span>
              </div>
            ))}
          </div>
        )}
      </div>
      {abilities.length > 0 && (
        <div className="ck-detail-sec">
          <h6>Drag onto a target</h6>
          <div className="ck-chips">{abilities.map(chip)}</div>
        </div>
      )}
      <div className="ck-detail-sec">
        <h6>Conditions — drag to apply</h6>
        <div className="ck-chips">
          {CONDITIONS.map((cd, i) => (
            <button key={i} className="ck-chip ck-chip-cond" title="drag onto a target"
              onPointerDown={(e) => startChip(e, { kind: "condition", cond: cd, name: cd })} onPointerMove={moveChip} onPointerUp={endChip}>
              <span className="ck-chip-name">{condIcon(cd) + " " + cd}</span>
            </button>
          ))}
        </div>
      </div>
      {pc ? <PCDetail pc={pc} />
        : sel.side === "mon" ? <div className="ck-scene ck-detail-sb" dangerouslySetInnerHTML={{ __html: E.renderSB(sel.mkey, { open: true }) }} /> : null}
    </div>
  );
}

/* ============================ HUD: CLOCK + CLUES + ROSTER ============================ */
function HUD({ st, up, onAddMonster, onAddPC, onAddParty }) {
  const lit = st.clues.filter(Boolean).length;
  const hasKey = lit >= 3;
  const toggleClue = (i) => up((s) => ({ clues: s.clues.map((v, j) => (j === i ? !v : v)) }));
  return (
    <aside className="ck-hud">
      <div className="ck-tile">
        <h3>🔎 Clues → the Key</h3>
        <div className="ck-clues">
          {CLUE_NAMES.map((nm, i) => (
            <button key={i} className={"ck-clue" + (st.clues[i] ? " lit" : "")} onClick={() => toggleClue(i)}>
              <span className="ck-cluestar">{st.clues[i] ? "★" : "✦"}</span> {nm}
            </button>
          ))}
        </div>
        <div className={"ck-keybadge" + (hasKey ? " on" : "")}>{hasKey ? "🔑 KEY HELD — Showdown ally (Ver B)" : `${lit}/3 clues to the Key`}</div>
      </div>

      <div className="ck-tile ck-roster">
        <h3>➕ Add to the fight</h3>
        {PARTY.length > 0 && <button className="ck-addparty" onClick={onAddParty}>+ Add party ({PARTY.length})</button>}
        <div className="ck-rosterbtns">
          {MON_ORDER.map((k) => (
            <button key={k} onClick={() => onAddMonster(k)} title={MON[k].usage || ""}>
              {MON[k].name} <small>CR {MON[k].cr} · {MON[k].maxhp}hp</small>
            </button>
          ))}
        </div>
        <PCAdd onAddPC={onAddPC} />
      </div>
    </aside>
  );
}

function PCAdd({ onAddPC }) {
  const [name, setName] = useState(""); const [init, setInit] = useState(""); const [ac, setAc] = useState(""); const [hp, setHp] = useState("");
  const add = () => {
    if (!name.trim()) return;
    onAddPC({ name: name.trim(), init: init === "" ? undefined : +init, ac: ac === "" ? undefined : +ac, maxhp: hp === "" ? undefined : +hp });
    setName(""); setInit(""); setAc(""); setHp("");
  };
  return (
    <div className="ck-pcadd">
      <div className="ck-pcrow">
        <input placeholder="PC name" value={name} onChange={(e) => setName(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter") add(); }} />
      </div>
      <div className="ck-pcrow ck-pcnums">
        <input placeholder="init" inputMode="numeric" value={init} onChange={(e) => setInit(e.target.value.replace(/[^0-9-]/g, ""))} />
        <input placeholder="AC" inputMode="numeric" value={ac} onChange={(e) => setAc(e.target.value.replace(/[^0-9]/g, ""))} />
        <input placeholder="HP" inputMode="numeric" value={hp} onChange={(e) => setHp(e.target.value.replace(/[^0-9]/g, ""))} />
        <button className="ck-pcbtn" onClick={add}>+ PC</button>
      </div>
    </div>
  );
}

/* ============================ LOOT / REWARDS ============================ */
/* Scene-reward items the DM hands out after clearing a scene. Definitions come from the data file
   (beat.loot, via TWGE.beats()); "given" state lives in st.lootGiven and persists with the save. */
function LootPanel({ beat, lootGiven, onToggle, onClose }) {
  const scenes = BEATS.map((b, i) => ({ b, i })).filter((x) => x.b.loot && x.b.loot.length);
  const total = scenes.reduce((n, x) => n + x.b.loot.length, 0);
  const given = scenes.reduce((n, x) => n + x.b.loot.filter((it) => lootGiven[it.id]).length, 0);
  return (
    <div className="ck-loot-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="ck-loot">
        <div className="ck-loot-head">
          <b className="ck-loot-title">🎁 Loot & rewards</b>
          <span className="ck-loot-prog">{given + "/" + total + " given"}</span>
          <button className="ck-loot-close" title="back to the cockpit" onClick={onClose}>✕ return</button>
        </div>
        <div className="ck-loot-hint">Hand these out after the party clears a scene — thematic, level-3 rewards. Toggles save with your session.</div>
        <div className="ck-loot-body">
          {scenes.length === 0
            ? <p className="ck-empty">No rewards defined for these scenes.</p>
            : scenes.map(({ b, i }) => (
                <div key={b.id} className={"ck-loot-scene" + (i === beat ? " current" : "")}>
                  <h4 className="ck-loot-scenehd">
                    <span>{(b.icon || "•") + " " + b.name}</span>
                    {i === beat ? <span className="ck-loot-here">you are here</span> : null}
                  </h4>
                  <div className="ck-loot-items">
                    {b.loot.map((it) => {
                      const on = !!lootGiven[it.id];
                      return (
                        <div key={it.id} className={"ck-loot-item" + (on ? " given" : "")}>
                          <button className={"ck-loot-toggle" + (on ? " on" : "")} title={on ? "given — click to take back" : "mark as given to the party"} onClick={() => onToggle(it.id)}>{on ? "✓ given" : "give"}</button>
                          <div className="ck-loot-main">
                            <div className="ck-loot-namerow">
                              <b className="ck-loot-name">{it.name}</b>
                              {it.qty > 1 ? <span className="ck-loot-qty">{"×" + it.qty}</span> : null}
                              {it.rarity ? <span className={"ck-loot-rar ck-rar-" + it.rarity}>{it.rarity}</span> : null}
                            </div>
                            {it.note ? <div className="ck-loot-note">{it.note}</div> : null}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}
        </div>
      </div>
    </div>
  );
}

window.Cockpit = Cockpit;
ReactDOM.createRoot(document.getElementById("app")).render(<Cockpit />);
